CREATE TABLE ASData_PL.DAS_EmailIntegration
(
    [Email] NVARCHAR(255) NULL,
    [FirstName] NVARCHAR(255) NULL,
    [LastName] NVARCHAR(255) NULL,
    [EmployerAccountID] VARCHAR(100) NULL,
    [AccountCount] INT NULL,
    [LevyStatus] VARCHAR(8) NULL,
    [LastLogin] VARCHAR(10) NULL,
    [DateOfLastAPIAutoSync] VARCHAR(10) NULL,
    [ReservedFunding] VARCHAR(5) NULL,
    [HasActiveReservation] VARCHAR(5) NULL,
    [EmployerSize] VARCHAR(6) NULL,
    [SectorEstimate] NVARCHAR(MAX) NULL,
    [AccountCreationDate] VARCHAR(10) NULL,
    [Registrationtype] VARCHAR(11) NULL,
    [DateOfFirstStart] VARCHAR(10) NULL,
    [DateOfLastStart] VARCHAR(10) NULL,
    [DateOfLastCompletion] VARCHAR(10) NULL,
    [ActiveApprentices] VARCHAR(5) NULL,
    [ActiveVacancies] VARCHAR(5) NULL,
    [AccountUserRole] VARCHAR(10) NULL,
    [Foundationappinlast24months] VARCHAR(5) NULL,
    [ApprenticeshipUnit] VARCHAR(5) NULL,
    [Stage1a] VARCHAR(5) NULL,
    [Stage1b] VARCHAR(5) NULL,
    [Stage2] VARCHAR(5) NULL,
    [Stage3] VARCHAR(5) NULL,
    [Stage4a] VARCHAR(5) NULL,
    [Stage4b] VARCHAR(5) NULL,
    [Stage5] VARCHAR(5) NULL,
    [RegistrationProgressScore] INT NULL,
    [CurrentRegistrationStage] VARCHAR(32) NULL,
    [UkEmployerSize] VARCHAR(50) NULL,
    [PrimaryIndustry] VARCHAR(50) NULL,
    [PrimaryLocation] VARCHAR(50) NULL,
    [AppsgovSignUpDate] VARCHAR(10) NULL,
    [PersonOrigin] VARCHAR(50) NULL,
    [IncludeInUR] BIT NULL,
    [RecordSource] VARCHAR(8) NOT NULL,
    [Ukprn] VARCHAR(100) NULL,
    [ProviderType] VARCHAR(19) NOT NULL,
    [ProviderTypeId] VARCHAR(100) NULL,
    [Employerprovider] VARCHAR(5) NOT NULL,
    [IsProvider] VARCHAR(5) NOT NULL,
    [Providersactivelinkedapps] VARCHAR(5) NOT NULL,
    [Providersactivelinkedvacancies] VARCHAR(5) NOT NULL,
    [IsEmployer] VARCHAR(5) NOT NULL,
    [Primaryusertype] VARCHAR(17) NOT NULL,
	[AsDm_UpdatedDateTime] datetime2 default getdate()	
);
