Create Table [ASData_PL].[Assessor_Certificates]
(
[Id]											[uniqueidentifier]		PRIMARY KEY NOT NULL,
[AchievementDate]								[DateTime2](7)			NULL,
[BatchNumber]								    [Int]					NULL,
[CertificateReference]							[NVarchar](50)			NULL,
[CertificateReferenceId]						[Int]					NULL,
[ContactName]									[NVarchar](100)			NULL,
[ContactOrganisation]							[NVarchar](200)			NULL,
[ContactPostCode]								[NVarchar](20)			NULL,
[CourseOption]									[NVarchar](200)			NULL,
[CreatedAt]										[DateTime2](7)			NULL,
[CreateDay]										[Date]					NULL,	
[CreatedBy]										[NVarchar](250)			NULL,
[DeletedAt]										[DateTime2](7)			NULL,
[DeletedBy]										[NVarchar](250)			NULL,
[Department]									[NVarchar](200)			NULL,
[IsPrivatelyFunded]								[Bit]					NULL,
[LearnerFamilyName]								[NVarchar](200)			NULL,
[LearnerGivenNames]								[Nvarchar](100)			NULL,
[LearningStartDate]								[DateTime2](7)			NULL,
[OrganisationId]								[uniqueidentifier]		NULL,
[OverallGrade]									[NVarchar](100)			NULL,
[PrivatelyFundedStatus]							[NVarchar](20)			NULL,
[ProviderName]									[NVarchar](200)			NULL,
[ProviderUkPrn]									[Int]					NULL,
[Registration]									[NVarchar](100)			NULL,
[StandardCode]									[Int]					NULL,
[StandardLevel]									[Int]					NULL,
[StandardName]									[NVarchar](200)			NULL,
[StandardPublicationDate]						[DateTime2](7)			NULL,
[StandardReference]								[NVarchar](100)			NULL,
[StandardUId]									[NVarchar](50)			NULL,
[Status]										[NVarchar](20)			NULL,
[ToBePrinted]									[DateTime2](7)			NULL,
[UpdatedAt]										[DateTime2](7)			NULL,
[UpdatedBy]										[NVarchar](200)			NULL,
[AsDm_UpdatedDateTime]							[Datetime2](7)			default getdate()
)