CREATE TABLE [ASData_PL].[LTM_Application]
(
	[Id] [int]										NOT NULL,
	[EmployerAccountId] [bigint]					NOT NULL,
	[PledgeId] [int]								NOT NULL,
	[Details] [nvarchar](max)						NOT NULL,
	[NumberOfApprentices] [int]						NOT NULL,
	[StandardId] [varchar](20)						NOT NULL,
	[StartDate] [datetime2](7)						NOT NULL,
	[Amount] [int]										NULL,
	[AutomaticApproval] [bit]							NULL,
	[CostingModel] [int]								NULL,
	[StandardTitle][varchar](500)					    NULL,
	[StandardLevel][int]							    NULL,
	[StandardDuration][int]							    NULL,
	[StandardMaxFunding] [int]						    NULL,
	[StandardRoute] [varchar](500)					    NULL,
	[HasTrainingProvider] [bit]						NOT NULL,
	[Sectors] [int]									NOT NULL,	
	[CreatedOn] [datetime2](7)						NOT NULL,
	[Status] [Tinyint]								NOT NULL,
	[TotalAmount] [int]								NOT NULL,
	[AdditionalLocation] [nvarchar](2000)			NULL,
	[SpecificLocation] [nvarchar](2000)				NULL,
	[NumberOfApprenticesUsed] [int]					NOT NULL,
	[AmountUsed] [int]								NOT NULL,
	[UpdatedOn] [Datetime2](7)						NULL,
	[MatchSector] [bit]								NULL ,
	[MatchLevel] [bit]								NULL ,
	[MatchLocation] [bit]							NULL ,
	[MatchJobRole] [bit]							NULL ,
	[MatchPercentage] [tinyint]						NULL ,
	[AsDm_UpdatedDateTime] datetime2 default getdate()
) ON [PRIMARY]
