CREATE TABLE [ASData_PL].[FAT2_StandardSector](
	[Id]						[int]					NOT NULL,
	[Title]						[varchar](1000)			NOT NULL,
	[Level]						[int]					NOT NULL,
	[IntegratedDegree]			[varchar](100)			NULL,
	[OverviewOfRole]			[varchar](max)			NOT NULL,
	[ApprenticeshipStandardId]	[int]					NULL,
	[SectorId]					[uniqueidentifier]		NOT NULL,
	[Sector]					[varchar](500)			NOT NULL,
	[Keywords]					[varchar](max)			NULL,
	[TypicalJobTitles]			[varchar](max)			NULL,
	[StandardPageUrl]			[varchar](500)			NOT NULL,
	[Version]					[decimal](18, 0)		NULL,
	[RegulatedBody]				[varchar](1000)			NULL,
	[Skills]					[nvarchar](max)			NULL,
	[Knowledge]					[nvarchar](max)			NULL,
	[Behaviours]				[nvarchar](max)			NULL,
	[Duties]					[nvarchar](max)			NULL,
	[CoreAndOptions]			[bit]					NOT NULL,
	[AsDm_UpdatedDateTime]	[datetime2](7)	DEFAULT (getdate())
)