CREATE TABLE [ASData_PL].[FAT2_Framework](
	[Id]								[varchar](15)		NOT NULL,
	[FrameworkOccupationId]				[int]				NULL,
	[Title]								[varchar](1000)		NOT NULL,
	[FrameworkName]						[varchar](500)		NOT NULL,
	[PathwayName]						[varchar](500)		NOT NULL,
	[ProgType]							[int]				NOT NULL,
	[FrameworkCode]						[int]				NULL,
	[PathwayCode]						[int]				NULL,
	[Level]								[int]				NULL,
	[TypicalLengthFrom]					[int]				NULL,
	[TypicalLengthTo]					[int]				NULL,
	[TypicalLengthUnit]					[varchar](10)		NULL,
	[Duration]							[int]				NULL,
	[CurrentFundingCap]					[int]				NULL,
	[MaxFunding]						[int]				NULL,
	[Ssa1]								[decimal](18, 0)	NULL,
	[Ssa2]								[decimal](18, 0)	NULL,
	[EffectiveFrom]						[datetime]			NULL,
	[EffectiveTo]						[datetime]			NULL,
	[IsActiveFramework]					[bit]				NULL,
	[ProgrammeType]						[int]				NULL,
	[HasSubGroups]						[bit]				NULL,
	[ExtendedTitle]						[varchar](2000)		NOT NULL,
	[AsDm_UpdatedDateTime]				[datetime2](7)	DEFAULT (getdate())
)
