CREATE TABLE ASData_PL.DAS_EmailIntegration_Provider
(
    [Email] VARCHAR(255) NOT NULL,
    [FirstName] VARCHAR(255) NULL,
    [LastName] VARCHAR(255) NULL,
    [EmployerAccountID] VARCHAR(1) NOT NULL,
    [AccountCount] INT NOT NULL,
    [LevyStatus] VARCHAR(7) NOT NULL,
    [LastLogin] VARCHAR(10) NULL,
    [DateOfLastAPIAutoSync] VARCHAR(10) NULL,
    [ReservedFunding] VARCHAR(1) NOT NULL,
    [HasActiveReservation] VARCHAR(1) NOT NULL,
    [EmployerSize] VARCHAR(1) NOT NULL,
    [SectorEstimate] VARCHAR(1) NOT NULL,
    [AccountCreationDate] VARCHAR(10) NULL,
    [Registrationtype] VARCHAR(1) NOT NULL,
    [DateOfFirstStart] VARCHAR(10) NULL,
    [DateOfLastStart] VARCHAR(10) NULL,
    [DateOfLastCompletion] VARCHAR(10) NULL,
    [ActiveApprentices] VARCHAR(1) NOT NULL,
    [ActiveVacancies] VARCHAR(1) NOT NULL,
    [AccountUserRole] VARCHAR(1) NOT NULL,
    [Foundationappinlast24months] VARCHAR(1) NOT NULL,
    [ApprenticeshipUnit] VARCHAR(1) NOT NULL,

    [Stage1a] VARCHAR(1) NOT NULL,
    [Stage1b] VARCHAR(1) NOT NULL,
    [Stage2] VARCHAR(1) NOT NULL,
    [Stage3] VARCHAR(1) NOT NULL,
    [Stage4a] VARCHAR(1) NOT NULL,
    [Stage4b] VARCHAR(1) NOT NULL,
    [Stage5] VARCHAR(1) NOT NULL,

    [RegistrationProgressScore] INT NOT NULL,
    [CurrentRegistrationStage] VARCHAR(1) NOT NULL,
    [UkEmployerSize] VARCHAR(1) NOT NULL,
    [PrimaryIndustry] VARCHAR(1) NOT NULL,
    [PrimaryLocation] VARCHAR(1) NOT NULL,
    [AppsgovSignUpDate] VARCHAR(10) NULL,
    [PersonOrigin] VARCHAR(1) NOT NULL,
    [IncludeInUR] VARCHAR(1) NOT NULL,

    [RecordSource] VARCHAR(8) NOT NULL,
    [Ukprn] VARCHAR(100) NULL,

    [ProviderType] VARCHAR(19) NOT NULL,
    [ProviderTypeId] VARCHAR(100) NULL,

    [Employerprovider] VARCHAR(5) NOT NULL,
    [IsProvider] VARCHAR(4) NOT NULL,
    [Providersactivelinkedapps] VARCHAR(5) NOT NULL,
    [Providersactivelinkedvacancies] VARCHAR(5) NOT NULL,
    [IsEmployer] VARCHAR(5) NOT NULL,
    [AsDm_UpdatedDateTime] datetime2 default getdate()	
    );