
CREATE TABLE [lkp].[Pst_LOCAL_AUTHORITY_Pst_COMBINED_AUTHORITY](
	[Pst_LOCAL_AUTHORITY] [varchar](9) NOT NULL,
	[Pst_COMBINED_AUTHORITY] [varchar](9) NOT NULL,
 CONSTRAINT [PK_Pst_LOCAL_AUTHORITY_Pst_COMBINED_AUTHORITY_Pst_LOCAL_AUTHORITY] PRIMARY KEY CLUSTERED 
(
	[Pst_LOCAL_AUTHORITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) 
)
