CREATE TABLE [Stg].[GA_SessionDataDetail]
(
		[GASD_Id] BIGINT IDENTITY(1,1)		NOT NULL,
		FullVisitorId						NVarchar(200),
		ClientId							NVarchar(200),			
		VisitId								NVarchar(200),
		VisitNumber							NVarchar(200),
		VisitStartDateTime					NVarchar(200),
		VisitDate							NVarchar(200),
		VisitorId							NVarchar(200),
		UserId								NVarchar(200),		
		Hits_Page_PagePath					NVarchar(Max),
		Hits_Page_PagePathLevel1			NVarchar(Max),
		Hits_Page_PagePathLevel2			NVarchar(Max),
		Hits_Page_PagePathLevel3			NVarchar(Max),
		Hits_Page_PagePathLevel4			NVarchar(Max),
		Hits_Time							NVarchar(200),		
		Hits_IsEntrance						NVarchar(200),
		Hits_IsExit							NVarchar(200),
		EmployerId							NVarchar(200),
		ID2									NVarchar(200),
		ID3									NVarchar(200),
		ESFAToken							NVarchar(200),		
		EventCategory						NVarchar(4000),
		EventAction							NVarchar(4000),
		EventLabel							NVarchar(4000),
		EventLabel_ESFAToken				NVarchar(200),		
		EventLabel_Keyword					NVarchar(200),
		EventLabel_Postcode					NVarchar(200),
		EventLabel_WithinDistance			NVarchar(200),
		EventLabel_Level					NVarchar(200),
		EventValue							NVarchar(Max),
		CD_ClientId							NVarchar(200), 
		CD_SearchTerms						NVarchar(512), 
		CD_UserId							NVarchar(200), 
		CD_LevyFlag							NVarchar(200), 
		CD_EmployerId						NVarchar(200), 
		CD_ESFAToken						NVarchar(200), 
		CD_LegalEntityId					NVarchar(200)  
)
