CREATE TABLE Stg.RAA_Vacancies
(
  SourseSK INT IDENTITY(1,1) NOT NULL
 ,BinaryId VARCHAR(256) 
 ,TypeCode VARCHAR(256)
 ,EmployerAccountId VARCHAR(256)
 ,VacancyReference VARCHAR(256)
 ,VacancyStatus VARCHAR(256)
 ,OwnerType VARCHAR(256)
 ,SourceOrigin VARCHAR(256)
 ,SourceType VARCHAR(256)
 ,CreatedDateTimeStamp VARCHAR(256)
 ,CreatedByUserID VARCHAR(256)
 ,CreatedByUserName VARCHAR(256)
 ,CreatedByUserEmail VARCHAR(256)
 ,LastUpdatedTimeStamp VARCHAR(256)
 ,LastUpdatedByUserId VARCHAR(256)
 ,LastUpdatedByUserName VARCHAR(256)
 ,LastUpdatedByUserEmail VARCHAR(256)
 ,IsDeleted  VARCHAR(256)
 ,DeletedDateTimeStamp VARCHAR(256)
 ,ClosingDateTimeStamp VARCHAR(256)
 ,DisabilityConfident VARCHAR(256)
 ,EmployerAddressLine1 VARCHAR(256)
 ,EmployerAddressLine2 VARCHAR(256)
 ,EmployerPostCode VARCHAR(256)
 ,EmployerLatitude VARCHAR(256)
 ,EmployerLongitude VARCHAR(256)
 ,EmployerName VARCHAR(256)
 ,EmployerNameOption VARCHAR(256)
 ,LegalEntityName VARCHAR(256)
 ,GeoCodeMethod VARCHAR(256)
 ,LegalEntityId VARCHAR(256)
 ,NumberOfPositions VARCHAR(256)
 ,ProgrammeId VARCHAR(256)
 ,ShortDescription VARCHAR(256)
 ,StartDateTimeStamp VARCHAR(256)
 ,VacancyTitle VARCHAR(256)
 ,WageDuration VARCHAR(256)
 ,WageDurationUnit VARCHAR(256)
 ,WorkingWeekDescription VARCHAR(256)
 ,WeeklyHours VARCHAR(256)
 ,WageType VARCHAR(256)
 ,RunId bigint  default(-1)
 ,AsDm_CreatedDate datetime2 default(getdate()) 
 ,AsDm_UpdatedDate datetime2 default(getdatE())
 )
