CREATE PROCEDURE [dbo].[LoadRPLookupData]
(
   @RunId int
)
AS

-- ==================================================
-- Author:      Sarma Evani
-- Create Date: 29/06/2021
-- Description: Load ROATP Lookup Data
-- ==================================================

BEGIN TRY

    SET NOCOUNT ON

 DECLARE @LogID int

/* Start Logging Execution */

  INSERT INTO Mgmt.Log_Execution_Results
	  (
	    RunId
	   ,StepNo
	   ,StoredProcedureName
	   ,StartDateTime
	   ,Execution_Status
	  )
  SELECT 
        @RunId
	   ,'Step-3'
	   ,'LoadROATPLookupData'
	   ,getdate()
	   ,0

   SELECT @LogID=MAX(LogId) FROM Mgmt.Log_Execution_Results
   WHERE StoredProcedureName='LoadROATPLookupData'
     AND RunId=@RunID


IF @@TRANCOUNT=0
BEGIN
	BEGIN TRANSACTION

	DELETE FROM [Mtd].[RP_LookupOversightReviewStatus]

	/* Isert into [Mtd].[RP_LookupOversightReviewStatus] */
	INSERT INTO [Mtd].[RP_LookupOversightReviewStatus] 
	([Status],[Description]) 
	VALUES 
	(1, 'Successful'),
	(2, 'Successful - Already Active'),
	(3, 'Successful - Fitness For Funding'),
	(4, 'Unsuccessful'),
	(5, 'In Progress'),
	(6, 'Rejected'),
	(7, 'Withdrawn'),
	(8, 'Removed');



	DELETE FROM [Mtd].[RP_LookupPageTitles]
	/* insert into [Mtd].[RP_LookupPageTitles]*/
	INSERT INTO [Mtd].[RP_LookupPageTitles]
	([SequenceNumber],[SectionNumber],[PageId],[Title])	
	VALUES
			(0, 1, '1', 'Preamble'),
			(0, 1, '2', 'Provider route'),
			(0, 1, '3', 'Conditions of acceptance'),
			(1, 1, '10', 'Your organisation'),
			(1, 1, '11', 'Your organisation'),
			(1, 1, '12', 'Your organisation'),
			(1, 2, '20', 'Does your organisation have an ultimate parent company in the UK?'),
			(1, 2, '21', 'Enter your organisation''s ultimate parent company details'),
			(1, 2, '30', 'What is your organisation''s Information Commissioner''s Office (ICO) registration number?'),
			(1, 2, '40', 'Does your organisation have a website?'),
			(1, 3, '70', 'Confirm who''s in control - Companies House'),
			(1, 3, '80', 'Confirm who''s in control - Trustees'),
			(1, 3, '90', 'Confirm who''s in control - Add Trustees'),
			(1, 3, '100', 'Tell us your organisation''s type'),
			(1, 3, '101', 'What is your organisation''s partner?'),
			(1, 3, '110', 'Enter the individual''s details'),
			(1, 3, '111', 'Enter the organisation''s details'),
			(1, 3, '120', 'What is {{UKRLPLegalName}}''s date of birth?'),
			(1, 3, '130', 'Confirm who''s in control - Add People In Control'),
			(1, 4, '140', 'What is your organisation?'),
			(1, 4, '150', 'What is your organisation?'),
			(1, 4, '160', 'What type of educational institute is your organisation?'),
			(1, 4, '170', 'What type of public body is your organisation?'),
			(1, 4, '180', 'What type of school is your organisation?'),
			(1, 4, '200', 'Is your organisation registered and receiving funding from ESFA?'),
			(1, 4, '210', 'Is your organisation receiving funding from ESFA?'),
			(1, 4, '220', 'Is your organisation monitored and supported by the Office of Students?'),
			(1, 4, '230', 'How would you describe your organisation?'),
			(1, 4, '50', 'How long has your organisation been actively trading?'),
			(1, 4, '60', 'How long has your organisation been actively trading?'),
			(1, 4, '10001', 'Your organisation is not eligible to apply to join RoATP'),
			(1, 4, '10002', 'Your organisation is not eligible to apply to join RoATP'),
			(1, 4, '10003', 'Your organisation is not eligible to apply to join RoATP'),
			(1, 5, '235', 'Is your organisation funded by the Office for Students?'),
			(1, 5, '240', 'Does your organisation offer initial teacher training?'),
			(1, 5, '250', 'Is the postgraduate teaching apprenticeship the only apprenticeship your organisation intends to deliver?'),
			(1, 5, '260', 'Has your organisation had a full Ofsted inspection in further education and skills?'),
			(1, 5, '270', 'Did your organisation get a grade for apprenticeships in this full Ofsted inspection?'),
			(1, 5, '280', 'What grade did your organisation get for overall effectiveness in this full Ofsted inspection?'),
			(1, 5, '290', 'Has your organisation had a monitoring visit for apprenticeships in further education and skills?'),
			(1, 5, '292', 'Has your organisation had 2 consecutive monitoring visits with the grade ''insufficient progress''?'),
			(1, 5, '294', 'Was the most recent monitoring visit within the last 18 months?'),
			(1, 5, '300', 'What grade did your organisation get for apprenticeships in this full Ofsted inspection?'),
			(1, 5, '301', 'What grade did your organisation get for apprenticeships in this full Ofsted inspection?'),
			(1, 5, '310', 'Did your organisation get this grade within the last 3 years?'),
			(1, 5, '311', 'Did your organisation get this grade within the last 3 years?'),
			(1, 5, '320', 'Has your organisation maintained funding from an education agency since its full Ofsted inspection?'),
			(1, 5, '330', 'Has your organisation had a short Ofsted inspection within the last 3 years?'),
			(1, 5, '340', 'Has your organisation maintained the grade it got in its full Ofsted inspection in its short Ofsted inspection?'),
			(1, 5, '350', 'Has your organisation delivered apprenticeship training as a subcontractor in the last 12 months?'),
			(1, 5, '360', 'Upload a copy of a legally binding contract between your organisation and a main or employer provider'),
			(1, 5, '10004', 'Your organisation is not eligible to apply to join RoATP'),
			(1, 5, '10010', 'Your organisation is not eligible to apply to join RoATP'),
			(2, 1, '2000', 'Financial health assessment'),
			(2, 1, '2010', 'Financial health assessment'),
			(2, 2, '2100', 'Was your organisation''s total annual turnover over £75 million for the latest reported financial year?'),
			(2, 2, '2110', 'Does your organisation expect its funding from ESFA to be less than 5% of its total annual turnover?'),
			(2, 2, '2120', 'Financial evidence'),
			(2, 2, '2130', 'Financial evidence'),
			(2, 2, '2140', 'Financial evidence'),
			(2, 2, '2150', 'Has your organisation produced its latest full financial statements covering a minimum of 12 months?'),
			(2, 2, '2160', 'Upload your organisation''s latest full financial statements covering the last 12 months'),
			(2, 2, '2170', 'Has your organisation produced financial statements covering any period within the last 12 months?'),
			(2, 2, '2180', 'What you need to upload'),
			(2, 2, '2190', 'Upload your organisation''s financial statements covering any period within the last 12 months'),
			(2, 2, '2195', 'What you need to upload'),
			(2, 2, '2200', 'Upload your organisation''s management accounts covering the remaining period to date'),
			(2, 2, '2210', 'Has your organisation produced full management accounts covering the last 12 months?'),
			(2, 2, '2220', 'What you need to upload'),
			(2, 2, '2225', 'Upload your organisation''s full management accounts for the last 12 months'),
			(2, 2, '2230', 'What you need to upload'),
			(2, 2, '2240', 'Upload your organisation''s management accounts covering at least 3 months within the last 12 months'),
			(2, 2, '2250', 'Upload your organisation''s financial projections covering the remaining period'),
			(2, 2, '2260', 'Who prepared the answers and uploads in this section?'),
			(2, 2, '2270', 'What''s the accounting reference date for the financial information you are submitting?'),
			(2, 2, '2280', 'How many months does the accounting period cover for the financial information you are submitting?'),
			(2, 3, '2500', 'Does your UK ultimate parent company have consolidated financial statements?'),
			(2, 3, '2510', 'Upload your UK ultimate parent company''s consolidated financial statements'),
			(2, 3, '2520', 'Does your UK ultimate parent company have other active subsidiary companies?'),
			(2, 3, '2530', 'Upload a financial statement for all your UK ultimate parent company''s active subsidiary companies'),
			(2, 3, '2540', 'Upload your UK ultimate parent company''s full financial statements covering the last 12 months'),
			(3, 1, '3000', 'Criminal and compliance checks on your organisation'),
			(3, 2, '3100', 'Checks on your organisation'),
			(3, 2, '3110', 'Checks on your organisation'),
			(3, 2, '3120', 'Checks on your organisation'),
			(3, 2, '3130', 'Checks on your organisation'),
			(3, 2, '3135', 'Checks on your organisation'),
			(3, 2, '3140', 'Checks on your organisation'),
			(3, 2, '3150', 'Checks on your organisation'),
			(3, 2, '3160', 'Checks on your organisation'),
			(3, 2, '3170', 'Checks on your organisation'),
			(3, 2, '3180', 'Checks on your organisation'),
			(3, 2, '3190', 'Checks on your organisation'),
			(3, 2, '3199', 'Checks on your organisation'),
			(3, 3, '3200', 'Criminal and compliance checks on who''s in control of your organisation'),
			(3, 4, '3300', 'Checks on who''s in control of your organisation'),
			(3, 4, '3301', 'Checks on who''s in control of your organisation'),
			(3, 4, '3310', 'Checks on who''s in control of your organisation'),
			(3, 4, '3311', 'Checks on who''s in control of your organisation'),
			(3, 4, '3320', 'Checks on who''s in control of your organisation'),
			(3, 4, '3321', 'Checks on who''s in control of your organisation'),
			(3, 4, '3330', 'Checks on who''s in control of your organisation'),
			(3, 4, '3331', 'Checks on who''s in control of your organisation'),
			(3, 4, '3340', 'Checks on who''s in control of your organisation'),
			(3, 4, '3341', 'Checks on who''s in control of your organisation'),
			(3, 4, '3350', 'Checks on who''s in control of your organisation'),
			(3, 4, '3351', 'Checks on who''s in control of your organisation'),
			(3, 4, '3360', 'Checks on who''s in control of your organisation'),
			(3, 4, '3361', 'Checks on who''s in control of your organisation'),
			(3, 4, '3370', 'Checks on who''s in control of your organisation'),
			(3, 4, '3371', 'Checks on who''s in control of your organisation'),
			(3, 4, '3380', 'Checks on who''s in control of your organisation'),
			(3, 4, '3381', 'Checks on who''s in control of your organisation'),
			(3, 4, '3390', 'Checks on who''s in control of your organisation'),
			(3, 4, '3391', 'Checks on who''s in control of your organisation'),
			(3, 4, '3395', 'Checks on who''s in control of your organisation'),
			(3, 4, '3396', 'Checks on who''s in control of your organisation'),
			(4, 1, '4000', 'Protecting your apprentices'),
			(4, 1, '4001', 'Protecting your apprentices'),
			(4, 1, '4002', 'Protecting your apprentices'),
			(4, 2, '4010', 'Continuity plan for apprenticeship training'),
			(4, 3, '4020', 'Equality and diversity policy'),
			(4, 4, '4030', 'Safeguarding and Prevent duty policy'),
			(4, 4, '4035', 'Tell us who has overall responsibility for safeguarding in your organisation'),
			(4, 4, '4037', 'Does your organisation''s safeguarding policy include its responsibilities towards the Prevent duty?'),
			(4, 4, '4038', 'Upload your organisation''s Prevent duty policy'),
			(4, 5, '4040', 'Health and safety policy'),
			(4, 5, '4045', 'Tell us who has overall responsibility for health and safety in your organisation'),
			(4, 6, '4050', 'Acting as a subcontractor'),
			(5, 1, '5000', 'Readiness to engage'),
			(5, 1, '5010', 'Readiness to engage'),
			(5, 1, '5020', 'Readiness to engage'),
			(5, 2, '5100', 'Engaging with employers'),
			(5, 2, '5110', 'Engaging with employers'),
			(5, 2, '5120', 'Tell us who''s responsible for managing relationships with employers'),
			(5, 2, '5130', 'Engaging with employers'),
			(5, 3, '5200', 'Complaints policy'),
			(5, 3, '5210', 'Complaints policy'),
			(5, 4, '5300', 'Contract for services template'),
			(5, 5, '5400', 'Commitment statement template'),
			(5, 6, '5500', 'Prior learning of apprentices'),
			(5, 6, '5510', 'Prior learning of apprentices'),
			(5, 7, '5550', 'English and maths assessments'),
			(5, 7, '5560', 'English and maths assessments'),
			(5, 7, '5570', 'English and maths assessments holding page'),
			(5, 8, '5600', 'Working with subcontractors'),
			(5, 8, '5610', 'Working with subcontractors'),
			(6, 1, '6000', 'Planning apprenticeship training'),
			(6, 1, '6001', 'Planning apprenticeship training'),
			(6, 1, '6002', 'Planning apprenticeship training'),
			(6, 2, '6201', 'Type of apprenticeship training'),
			(6, 2, '6202', 'Type of apprenticeship training'),
			(6, 2, '6203', 'Type of apprenticeship training'),
			(6, 2, '6230', 'Application standards'),
			(6, 2, '6250', 'Apprenticeship frameworks'),
			(6, 2, '6252', 'Organisation transition'),
			(6, 2, '6253', 'Organisation transition'),
			(6, 2, '6254', 'Why will your organisation only deliver apprenticeship frameworks?'),
			(6, 2, '6260', 'Application frameworks'),
			(6, 2, '6262', 'Organisation transition'),
			(6, 2, '6264', 'Why will your organisation only deliver apprenticeship frameworks?'),
			(6, 2, '6270', 'How will your organisation engage with end-point assessment organisations (EPAOs)?'),
			(6, 2, '6280', 'How will your organisation plan to engage and work with awarding bodies?'),
			(6, 3, '6300', 'How will your organisation train its apprentices?'),
			(6, 4, '6400', 'How will your organisation ensure apprentices are supported during their apprenticeship training?'),
			(6, 4, '6405', 'How will your organisation ensure apprentices are supported during their apprenticeship training?'),
			(6, 4, '6410', 'How will your organisation support its apprentices?'),
			(6, 4, '6420', 'What other ways will your organisation use to support its apprentices?'),
			(6, 5, '6500', 'Forecasting starts'),
			(6, 5, '6510', 'Ready to deliver against starts'),
			(6, 5, '6520', 'Recruit staff to deliver'),
			(6, 5, '6530', 'Staff Apprentice Ratio'),
			(6, 5, '6540', 'Proposed staff to learner support'),
			(6, 6, '6600', 'What teaching methods will your organisation use to deliver 20% off the job training?'),
			(6, 6, '6610', 'How will your organisation ensure 20% off the job training is relevant to the specific apprenticeship being delivered?'),
			(6, 7, '6700', 'Where will your apprentices be trained?'),
			(7, 1, '7000', 'Delivering apprenticeship training'),
			(7, 1, '7001', 'Delivering apprenticeship training'),
			(7, 1, '7002', 'Delivering apprenticeship training'),
			(7, 2, '7100', 'Tell us who has overall accountability for apprenticeships in your organisation'),
			(7, 3, '7200', 'Confirm management hierarchy'),
			(7, 4, '7300', 'Upload your management hierarchy''s expectations for quality and high standards in apprenticeship training'),
			(7, 4, '7305', 'Tell us how these expectations for quality and high standards in apprenticeship training are monitored and evaluated'),
			(7, 4, '7310', 'Tell us who''s responsible for maintaining these expectations for quality and high standards in apprenticeship training'),
			(7, 4, '7320', 'How are these expectations for quality and high standards in apprenticeship training communicated to employees'),
			(7, 5, '7500', 'Developing and delivering training'),
			(7, 5, '7510', 'Developing and delivering training'),
			(7, 5, '7520', 'Developing and delivering training'),
			(7, 5, '7530', 'Developing and delivering training'),
			(7, 5, '7540', 'Tell us who''s the overall manager for this team'),
			(7, 5, '7560', 'Developing and delivering training'),
			(7, 5, '7570', 'How has the team worked with other organisations to develop and deliver training?'),
			(7, 5, '7590', 'Tell us who''s the overall manager for this team'),
			(7, 5, '7591', 'How has the team worked with other organisations and employers to develop and deliver training?'),
			(7, 5, '7592', 'How has the team worked with employers to develop and deliver training?'),
			(7, 5, '7593', 'How has this person worked with other organisations to develop and deliver training?'),
			(7, 5, '7594', 'How has this person worked with other organisations and employers to develop and deliver training?'),
			(7, 5, '7595', 'How has this person worked with employers to develop and deliver training?'),
			(7, 6, '7600', 'Your organisation''s sectors'),
			(7, 6, '7610AA', 'Agriculture, environmental and animal care'),
			(7, 6, '7610A', 'Agriculture, environmental and animal care'),
			(7, 6, '7610B', 'Agriculture, environmental and animal care'),
			(7, 6, '7610', 'Agriculture, environmental and animal care'),
			(7, 6, '7611', '{{DATAgricultureFirstName}} {{DATAgricultureLastName}}''s experience in the ''Agriculture, environmental and animal care'' sector'),
			(7, 6, '7612', '{{DATAgricultureFirstName}} {{DATAgricultureLastName}}''s experience in the ''Agriculture, environmental and animal care'' sector'),
			(7, 6, '7613', '{{DATAgricultureFirstName}} {{DATAgricultureLastName}}''s experience in the ''Agriculture, environmental and animal care'' sector'),
			(7, 6, '7615AA', 'Business and administration'),
			(7, 6, '7615A', 'Business and administration'),
			(7, 6, '7615B', 'Business and administration'),
			(7, 6, '7615', 'Business and administration'),
			(7, 6, '7616', '{{DATBusinessFirstName}} {{DATBusinessLastName}}''s experience in the ''Business and administration'' sector'),
			(7, 6, '7617', '{{DATBusinessFirstName}} {{DATBusinessLastName}}''s experience in the ''Business and administration'' sector'),
			(7, 6, '7618', '{{DATBusinessFirstName}} {{DATBusinessLastName}}''s experience in the ''Business and administration'' sector'),
			(7, 6, '7620AA', 'Care services'),
			(7, 6, '7620A', 'Care services'),
			(7, 6, '7620B', 'Care services'),
			(7, 6, '7620', 'Care services'),
			(7, 6, '7621', '{{DATCareServicesFirstName}} {{DATCareServicesLastName}}''s experience in the ''Care services'' sector'),
			(7, 6, '7622', '{{DATCareServicesFirstName}} {{DATCareServicesLastName}}''s experience in the ''Care services'' sector'),
			(7, 6, '7623', '{{DATCareServicesFirstName}} {{DATCareServicesLastName}}''s experience in the ''Care services'' sector'),
			(7, 6, '7625AA', 'Catering and hospitality'),
			(7, 6, '7625A', 'Catering and hospitality'),
			(7, 6, '7625B', 'Catering and hospitality'),
			(7, 6, '7625', 'Catering and hospitality'),
			(7, 6, '7626', '{{DATCateringFirstName}} {{DATCateringLastName}}''s experience in the ''Catering and hospitality'' sector'),
			(7, 6, '7627', '{{DATCateringFirstName}} {{DATCateringLastName}}''s experience in the ''Catering and hospitality'' sector'),
			(7, 6, '7628', '{{DATCateringFirstName}} {{DATCateringLastName}}''s experience in the ''Catering and hospitality'' sector'),
			(7, 6, '7630AA', 'Construction'),
			(7, 6, '7630A', 'Construction'),
			(7, 6, '7630B', 'Construction'),
			(7, 6, '7630', 'Construction'),
			(7, 6, '7631', '{{DATConstructionFirstName}} {{DATConstructionLastName}}''s experience in the ''Construction'' sector'),
			(7, 6, '7632', '{{DATConstructionFirstName}} {{DATConstructionLastName}}''s experience in the ''Construction'' sector'),
			(7, 6, '7633', '{{DATConstructionFirstName}} {{DATConstructionLastName}}''s experience in the ''Construction'' sector'),
			(7, 6, '7635AA', 'Creative and design'),
			(7, 6, '7635A', 'Creative and design'),
			(7, 6, '7635B', 'Creative and design'),
			(7, 6, '7635', 'Creative and design'),
			(7, 6, '7636', '{{DATCreativeFirstName}} {{DATCreativeLastName}}''s experience in the ''Creative and design'' sector'),
			(7, 6, '7637', '{{DATCreativeFirstName}} {{DATCreativeLastName}}''s experience in the ''Creative and design'' sector'),
			(7, 6, '7638', '{{DATCreativeFirstName}} {{DATCreativeLastName}}''s experience in the ''Creative and design'' sector'),
			(7, 6, '7640AA', 'Digital'),
			(7, 6, '7640A', 'Digital'),
			(7, 6, '7640B', 'Digital'),
			(7, 6, '7640', 'Digital'),
			(7, 6, '7641', '{{DATDigitalFirstName}} {{DATDigitalLastName}}''s experience in the ''Digital'' sector'),
			(7, 6, '7642', '{{DATDigitalFirstName}} {{DATDigitalLastName}}''s experience in the ''Digital'' sector'),
			(7, 6, '7643', '{{DATDigitalFirstName}} {{DATDigitalLastName}}''s experience in the ''Digital'' sector'),
			(7, 6, '7645AA', 'Education and childcare'),
			(7, 6, '7645A', 'Education and childcare'),
			(7, 6, '7645B', 'Education and childcare'),
			(7, 6, '7645', 'Education and childcare'),
			(7, 6, '7646', '{{DATEducationFirstName}} {{DATEducationLastName}}''s experience in the ''Education and childcare'' sector'),
			(7, 6, '7647', '{{DATEducationFirstName}} {{DATEducationLastName}}''s experience in the ''Education and childcare'' sector'),
			(7, 6, '7648', '{{DATEducationFirstName}} {{DATEducationLastName}}''s experience in the ''Education and childcare'' sector'),
			(7, 6, '7650AA', 'Engineering and manufacturing'),
			(7, 6, '7650A', 'Engineering and manufacturing'),
			(7, 6, '7650B', 'Engineering and manufacturing'),
			(7, 6, '7650', 'Engineering and manufacturing'),
			(7, 6, '7651', '{{DATEngineeringFirstName}} {{DATEngineeringLastName}}''s experience in the ''Engineering and manufacturing'' sector'),
			(7, 6, '7652', '{{DATEngineeringFirstName}} {{DATEngineeringLastName}}''s experience in the ''Engineering and manufacturing'' sector'),
			(7, 6, '7653', '{{DATEngineeringFirstName}} {{DATEngineeringLastName}}''s experience in the ''Engineering and manufacturing'' sector'),
			(7, 6, '7655AA', 'Hair and Beauty'),
			(7, 6, '7655A', 'Hair and Beauty'),
			(7, 6, '7655', 'Hair and Beauty'),
			(7, 6, '7655B', 'Hair and Beauty'),
			(7, 6, '7656', '{{DATHairAndBeautyFirstName}} {{DATHairAndBeautyLastName}}''s experience in the ''Hair and Beauty'' sector'),
			(7, 6, '7657', '{{DATHairAndBeautyFirstName}} {{DATHairAndBeautyLastName}}''s experience in the ''Hair and Beauty'' sector'),
			(7, 6, '7658', '{{DATHairAndBeautyFirstName}} {{DATHairAndBeautyLastName}}''s experience in the ''Hair and Beauty'' sector'),
			(7, 6, '7660AA', 'Health and science'),
			(7, 6, '7660A', 'Health and science'),
			(7, 6, '7660B', 'Health and science'),
			(7, 6, '7660', 'Health and science'),
			(7, 6, '7661', '{{DATHealthAndScienceFirstName}} {{DATHealthAndScienceLastName}}''s experience in the ''Health and science'' sector'),
			(7, 6, '7662', '{{DATHealthAndScienceFirstName}} {{DATHealthAndScienceLastName}}''s experience in the ''Health and science'' sector'),
			(7, 6, '7663', '{{DATHealthAndScienceFirstName}} {{DATHealthAndScienceLastName}}''s experience in the ''Health and science'' sector'),
			(7, 6, '7665AA', 'Legal, finance and accounting'),
			(7, 6, '7665A', 'Legal, finance and accounting'),
			(7, 6, '7665B', 'Legal, finance and accounting'),
			(7, 6, '7665', 'Legal, finance and accounting'),
			(7, 6, '7666', '{{DATLegalFirstName}} {{DATLegalLastName}}''s experience in the ''Legal, finance and accounting'' sector'),
			(7, 6, '7667', '{{DATLegalFirstName}} {{DATLegalLastName}}''s experience in the ''Legal, finance and accounting'' sector'),
			(7, 6, '7668', '{{DATLegalFirstName}} {{DATLegalLastName}}''s experience in the ''Legal, finance and accounting'' sector'),
			(7, 6, '7670AA', 'Protective services'),
			(7, 6, '7670A', 'Protective services'),
			(7, 6, '7670B', 'Protective services'),
			(7, 6, '7670', 'Protective services'),
			(7, 6, '7671', '{{DATProtectiveServicesFirstName}} {{DATProtectiveServicesLastName}}''s experience in the ''Protective services'' sector'),
			(7, 6, '7672', '{{DATProtectiveServicesFirstName}} {{DATProtectiveServicesLastName}}''s experience in the ''Protective services'' sector'),
			(7, 6, '7673', '{{DATProtectiveServicesFirstName}} {{DATProtectiveServicesLastName}}''s experience in the ''Protective services'' sector'),
			(7, 6, '7675AA', 'Sales, marketing and procurement'),
			(7, 6, '7675A', 'Sales, marketing and procurement'),
			(7, 6, '7675B', 'Sales, marketing and procurement'),
			(7, 6, '7675', 'Sales, marketing and procurement'),
			(7, 6, '7676', '{{DATSalesFirstName}} {{DATSalesLastName}}''s experience in the ''Sales, marketing and procurement'' sector'),
			(7, 6, '7677', '{{DATSalesFirstName}} {{DATSalesLastName}}''s experience in the ''Sales, marketing and procurement'' sector'),
			(7, 6, '7678', '{{DATSalesFirstName}} {{DATSalesLastName}}''s experience in the ''Sales, marketing and procurement'' sector'),
			(7, 6, '7680AA', 'Transport and logistics'),
			(7, 6, '7680A', 'Transport and logistics'),
			(7, 6, '7680B', 'Transport and logistics'),
			(7, 6, '7680', 'Transport and logistics'),
			(7, 6, '7681', '{{DATTransportFirstName}} {{DATTransportLastName}}''s experience in the ''Transport and logistics'' sector'),
			(7, 6, '7682', '{{DATTransportFirstName}} {{DATTransportLastName}}''s experience in the ''Transport and logistics'' sector'),
			(7, 6, '7683', '{{DATTransportFirstName}} {{DATTransportLastName}}''s experience in the ''Transport and logistics'' sector'),
			(7, 7, '7700', 'Upload your organisation''s contract for services template with employers'),
			(7, 7, '7710', 'Give an example of how your organisation used this policy to improve employee sector expertise'),
			(7, 7, '7720', 'Give an example of how your organisation used this policy to maintain employee teaching and training knowledge'),
			(8, 1, '8000', 'Evaluating apprenticeship training'),
			(8, 1, '8010', 'Evaluating apprenticeship training'),
			(8, 2, '8100', 'Process for evaluating the quality of training delivered'),
			(8, 2, '8110', 'Process for evaluating the quality of training delivered'),
			(8, 3, '8200', 'Process of evaluating the quality of apprenticeship training'),
			(8, 3, '8210', 'Process of evaluating the quality of apprenticeship training'),
			(8, 3, '8220', 'Process of evaluating the quality of apprenticeship training'),
			(8, 3, '8230', 'Process of evaluating the quality of apprenticeship training'),
			(8, 4, '8300', 'Systems and processes to collect apprenticeship data'),
			(8, 4, '8310', 'Systems and processes to collect apprenticeship data'),
			(8, 4, '8320', 'Who is the individual accountable for submitting ILR data for your organisation?'),
			(9, 1, '9000', 'Do you have permission from everyone named in this application to use their details?'),
			(9, 1, '9010', 'Have you checked with everyone named in this application that the details provided for them are accurate?'),
			(9, 1, '9020', 'Do you have permission from your organisation to submit this application?'),
			(9, 1, '10005', 'Before you submit your application'),
			(9, 2, '9100', 'Quality statement'),
			(9, 2, '100055', 'Before you submit your application'),
			(9, 3, '9200', 'Do you understand that your organisation will not join the RoATP until it completes all post application tasks?'),
			(9, 3, '10006', 'Before you submit your application');

			DELETE FROM [Mtd].[RP_LookupQuestionTitles]
			/* Insert into [Mtd].[RP_LookupQuestionTitles]*/
			INSERT INTO [Mtd].[RP_LookupQuestionTitles]
			([SequenceNumber][SectionNumber],[PageId],[QuestionId],[Title])
				VALUES 				
					(0, 1, '1', 'PRE-10', 'UKPRN'),
					(0, 1, '1', 'PRE-20', 'UkrlpLegalName'),
					(0, 1, '1', 'PRE-30', 'UkrlpWebsite'),
					(0, 1, '1', 'PRE-31', 'UKrlpNoWebsite'),
					(0, 1, '1', 'PRE-40', 'UkrlpLegalAddressLine1'),
					(0, 1, '1', 'PRE-41', 'UkrlpLegalAddressLine2'),
					(0, 1, '1', 'PRE-42', 'UkrlpLegalAddressLine3'),
					(0, 1, '1', 'PRE-43', 'UkrlpLegalAddressLine4'),
					(0, 1, '1', 'PRE-44', 'UkrlpLegalAddressTown'),
					(0, 1, '1', 'PRE-45', 'UkrlpLegalAddressPostcode'),
					(0, 1, '1', 'PRE-46', 'UkrlpTradingName'),
					(0, 1, '1', 'PRE-50', 'CompaniesHouseManualEntryRequired'),
					(0, 1, '1', 'PRE-51', 'UkrlpVerificationCompanyNumber'),
					(0, 1, '1', 'PRE-52', 'CompaniesHouseCompanyName'),
					(0, 1, '1', 'PRE-53', 'CompaniesHouseCompanyType'),
					(0, 1, '1', 'PRE-54', 'CompaniesHouseCompanyStatus'),
					(0, 1, '1', 'PRE-55', 'CompaniesHouseIncorporationDate'),
					(0, 1, '1', 'PRE-56', 'UkrlpVerificationCompany'),
					(0, 1, '1', 'PRE-60', 'CharityCommissionTrusteeManualEntry'),
					(0, 1, '1', 'PRE-61', 'UkrlpVerificationCharityRegNumber'),
					(0, 1, '1', 'PRE-62', 'CharityCommissionCharityName'),
					(0, 1, '1', 'PRE-64', 'CharityCommissionRegistrationDate'),
					(0, 1, '1', 'PRE-65', 'UkrlpVerificationCharity'),
					(0, 1, '1', 'PRE-70', 'UkrlpVerificationSoleTraderPartnership'),
					(0, 1, '1', 'PRE-80', 'UkrlpPrimaryVerificationSource'),
					(0, 1, '1', 'PRE-90', 'OnRoatp'),
					(0, 1, '1', 'PRE-91', 'RoatpCurrentStatus'),
					(0, 1, '1', 'PRE-92', 'RoatpRemovedReason'),
					(0, 1, '1', 'PRE-93', 'RoatpStatusDate'),
					(0, 1, '1', 'PRE-94', 'RoatpProviderRoute'),
					(0, 1, '1', 'PRE-95', 'LevyPayingEmployer'),
					(0, 1, '2', 'YO-1', 'ApplyProviderRoute'),
					(0, 1, '3', 'COA-1', 'COAStage1Application'),
					(1, 2, '20', 'YO-20', 'HasParentCompany'),
					(1, 2, '21', 'YO-21', 'Company number'),
					(1, 2, '21', 'YO-22', 'Company name'),
					(1, 2, '30', 'YO-30', 'ICO registration number'),
					(1, 2, '40', 'YO-40', 'HasWebsite'),
					(1, 2, '40', 'YO-41', 'Website address'),
					(1, 3, '100', 'YO-100', 'SoleTradeOrPartnership'),
					(1, 3, '101', 'YO-101', 'PartnershipType'),
					(1, 3, '110', 'YO-110', 'Individual''s details'),
					(1, 3, '111', 'YO-111', 'Organisation''s details'),
					(1, 3, '120', 'YO-120', 'Date of birth'),
					(1, 3, '130', 'YO-130', 'AddPeopleInControl'),
					(1, 3, '70', 'YO-70', 'CompaniesHouseDirectors'),
					(1, 3, '70', 'YO-71', 'CompaniesHousePSCs'),
					(1, 3, '70', 'YO-75', 'DirectorsPSCsConfirmed'),
					(1, 3, '80', 'YO-80', 'CharityTrustees'),
					(1, 3, '80', 'YO-85', 'ConfirmTrustees'),
					(1, 3, '90', 'YO-90', 'AddTrustees'),
					(1, 4, '10001', 'SHUT-001', 'Shutter Page - Actively trading for at least 12 months'),
					(1, 4, '10002', 'SHUT-002', 'Shutter Page - Actively trading for at least 12 months'),
					(1, 4, '10003', 'SHUT-003', 'Shutter Page - Actively trading for at least 3 months'),
					(1, 4, '140', 'YO-140', 'OrganisationTypeMainSupporting'),
					(1, 4, '150', 'YO-150', 'OrganisationTypeEmployer'),
					(1, 4, '160', 'YO-160', 'OrganisationEducationInstitute'),
					(1, 4, '170', 'YO-170', 'OrganisationPublicBody'),
					(1, 4, '180', 'YO-180', 'OrganisationSchool'),
					(1, 4, '200', 'YO-200', 'OrganisationRegisteredESFA'),
					(1, 4, '210', 'YO-210', 'OrganisationFundedESFA'),
					(1, 4, '220', 'YO-220', 'OrganisationMonitoredOFS'),
					(1, 4, '230', 'YO-230', 'OrganisationDescription'),
					(1, 4, '50', 'YO-50', 'ActivelyTrading'),
					(1, 4, '60', 'YO-60', 'ActivelyTradingSupporting'),
					(1, 5, '235', 'YO-235', 'OFSFunded'),
					(1, 5, '240', 'YO-240', 'ITTAccredited'),
					(1, 5, '250', 'YO-250', 'ITTPGTA'),
					(1, 5, '260', 'YO-260', 'OfstedFESkills'),
					(1, 5, '270', 'YO-270', 'OfstedApprenticeshipGrade'),
					(1, 5, '280', 'YO-280', 'OfstedOEGrade'),
					(1, 5, '290', 'YO-290', 'HasHadMonitoringVisit'),
					(1, 5, '292', 'YO-292', 'Has2MonitoringVisitsGradedInadequate'),
					(1, 5, '294', 'YO-294', 'HasMonitoringVisitGradedInadequateInLast18Months'),
					(1, 5, '300', 'YO-300', 'OfstedApprenticeshipsGrade'),
					(1, 5, '301', 'YO-301', 'OfstedApprenticeshipsGradeOFS'),
					(1, 5, '310', 'YO-310', 'OfstedGradeLast3Years'),
					(1, 5, '311', 'YO-311', 'OfstedGradeLast3Years'),
					(1, 5, '320', 'YO-320', 'MaintainedFunding'),
					(1, 5, '330', 'YO-330', 'HadShortInspection'),
					(1, 5, '340', 'YO-340', 'MaintainedShortInspectionGrade'),
					(1, 5, '350', 'YO-350', 'HasDeliveredTrainingAsSubcontractor'),
					(1, 5, '360', 'YO-360', 'ContractFileName'),
					(2, 2, '2100', 'FH-30', 'Was your organisation''s total annual turnover over £75 million for the latest reported financial year?'),
					(2, 2, '2110', 'FH-40', 'Does your organisation expect its funding from ESFA to be less than 5% of its total annual turnover?'),
					(2, 2, '2120', 'FH-100', 'Enter your organisation''s total current liabilities for the latest reported financial year'),
					(2, 2, '2120', 'FH-110', 'Enter your organisation''s total borrowings for the latest reported financial year'),
					(2, 2, '2120', 'FH-120', 'Enter your organisation''s net assets for the latest reported financial year'),
					(2, 2, '2120', 'FH-130', 'Enter your organisation''s total intangible assets for the latest reported financial year'),
					(2, 2, '2120', 'FH-50', 'Enter your organisation''s total annual turnover for the latest reported financial year'),
					(2, 2, '2120', 'FH-550', 'Enter your organisation''s average number of Full Time Equivalent (FTE) employees for the last financial year'),
					(2, 2, '2120', 'FH-60', 'Enter your organisation''s total depreciation and amortisation charges for the latest reported financial year'),
					(2, 2, '2120', 'FH-70', 'Enter your organisation''s profit or loss for the latest reported financial year'),
					(2, 2, '2120', 'FH-80', 'Enter your organisation''s total dividends for the latest reported financial year'),
					(2, 2, '2120', 'FH-90', 'Enter your organisation''s total current assets for the latest reported financial year'),
					(2, 2, '2130', 'FH-140', 'Enter your organisation''s total annual turnover for the latest reported financial year'),
					(2, 2, '2130', 'FH-150', 'Enter your organisation''s total depreciation and amortisation charges for the latest reported financial year'),
					(2, 2, '2130', 'FH-160', 'Enter your organisation''s profit or loss for the latest reported financial year'),
					(2, 2, '2130', 'FH-170', 'Enter your organisation''s total dividends for the latest reported financial year'),
					(2, 2, '2130', 'FH-180', 'Enter your organisation''s total current assets for the latest reported financial year'),
					(2, 2, '2130', 'FH-190', 'Enter your organisation''s total current liabilities for the latest reported financial year'),
					(2, 2, '2130', 'FH-200', 'Enter your organisation''s total borrowings for the latest reported financial year'),
					(2, 2, '2130', 'FH-210', 'Enter your organisation''s net assets for the latest reported financial year'),
					(2, 2, '2130', 'FH-220', 'Enter your organisation''s total intangible assets for the latest reported financial year'),
					(2, 2, '2130', 'FH-225', 'Enter your organisation''s average number of Full Time Equivalent (FTE) employees for the last financial year'),
					(2, 2, '2140', 'FH-230', 'Enter your organisation''s total annual turnover for the latest reported financial year'),
					(2, 2, '2140', 'FH-240', 'Enter your organisation''s total depreciation and amortisation charges for the latest reported financial year'),
					(2, 2, '2140', 'FH-250', 'Enter your organisation''s profit or loss for the latest reported financial year'),
					(2, 2, '2140', 'FH-260', 'Enter your organisation''s total dividends for the latest reported financial year'),
					(2, 2, '2140', 'FH-270', 'Enter your organisation''s total current assets for the latest reported financial year'),
					(2, 2, '2140', 'FH-280', 'Enter your organisation''s total current liabilities for the latest reported financial year'),
					(2, 2, '2140', 'FH-290', 'Enter your organisation''s total borrowings for the latest reported financial year'),
					(2, 2, '2140', 'FH-300', 'Enter your organisation''s net assets for the latest reported financial year'),
					(2, 2, '2140', 'FH-310', 'Enter your organisation''s total intangible assets for the latest reported financial year'),
					(2, 2, '2140', 'FH-315', 'Enter your organisation''s average number of Full Time Equivalent (FTE) employees for the last financial year'),
					(2, 2, '2150', 'FH-320', 'Has your organisation produced its latest full financial statements covering a minimum of 12 months?'),
					(2, 2, '2150', 'FHA-320', 'Has your organisation produced its latest full financial statements covering a minimum of 12 months?'),
					(2, 2, '2160', 'FH-330', 'File 1'),
					(2, 2, '2160', 'FH-331', 'File 2'),
					(2, 2, '2160', 'FH-332', 'File 3'),
					(2, 2, '2160', 'FH-333', 'File 4'),
					(2, 2, '2170', 'FH-340', 'Has your organisation produced financial statements covering any period within the last 12 months?'),
					(2, 2, '2190', 'FH-350', 'File 1'),
					(2, 2, '2190', 'FH-351', 'File 2'),
					(2, 2, '2190', 'FH-352', 'File 3'),
					(2, 2, '2190', 'FH-353', 'File 4'),
					(2, 2, '2200', 'FH-360', 'File 1'),
					(2, 2, '2200', 'FH-361', 'File 2'),
					(2, 2, '2200', 'FH-362', 'File 3'),
					(2, 2, '2200', 'FH-363', 'File 4'),
					(2, 2, '2210', 'FH-370', 'Has your organisation produced full management accounts covering the last 12 months?'),
					(2, 2, '2225', 'FH-380', 'File 1'),
					(2, 2, '2225', 'FH-381', 'File 2'),
					(2, 2, '2225', 'FH-382', 'File 3'),
					(2, 2, '2225', 'FH-383', 'File 4'),
					(2, 2, '2240', 'FH-390', 'File 1'),
					(2, 2, '2240', 'FH-391', 'File 2'),
					(2, 2, '2240', 'FH-392', 'File 3'),
					(2, 2, '2240', 'FH-393', 'File 4'),
					(2, 2, '2250', 'FH-400', 'File 1'),
					(2, 2, '2250', 'FH-401', 'File 2'),
					(2, 2, '2250', 'FH-402', 'File 3'),
					(2, 2, '2250', 'FH-403', 'File 4'),
					(2, 2, '2260', 'FH-410', 'Who prepared the answers and uploads in this section?'),
					(2, 2, '2270', 'FH-420', 'What''s the accounting reference date for the financial information you are submitting?'),
					(2, 2, '2280', 'FH-430', 'How many months does the accounting period cover for the financial information you are submitting?'),
					(2, 3, '2500', 'FH-500', 'Does your UK ultimate parent company have consolidated financial statements?'),
					(2, 3, '2510', 'FH-510', 'File 1'),
					(2, 3, '2510', 'FH-511', 'File 2'),
					(2, 3, '2510', 'FH-512', 'File 3'),
					(2, 3, '2510', 'FH-513', 'File 4'),
					(2, 3, '2520', 'FH-520', 'Does your UK ultimate parent company have other active subsidiary companies?'),
					(2, 3, '2530', 'FH-530', 'File 1'),
					(2, 3, '2530', 'FH-531', 'File 2'),
					(2, 3, '2530', 'FH-532', 'File 3'),
					(2, 3, '2530', 'FH-533', 'File 4'),
					(2, 3, '2540', 'FH-540', 'File 1'),
					(2, 3, '2540', 'FH-541', 'File 2'),
					(2, 3, '2540', 'FH-542', 'File 3'),
					(2, 3, '2540', 'FH-543', 'File 4'),
					(3, 2, '3100', 'CC-20', 'Does your organisation have any composition with creditors?'),
					(3, 2, '3100', 'CC-20-1', 'Give us more information'),
					(3, 2, '3110', 'CC-21', 'Has your organisation failed to pay back funds in the last 3 years?'),
					(3, 2, '3100', 'CC-21-1', 'Give us more information'),
					(3, 2, '3120', 'CC-22', 'Has your organisation had a contract terminated early by a public body in the last 3 years?'),
					(3, 2, '3100', 'CC-22-1', 'Give us more information'),
					(3, 2, '3130', 'CC-23', 'Has your organisation withdrawn from a contract with a public body in the last 3 years?'),
					(3, 2, '3100', 'CC-23-1', 'Give us more information'),
					(3, 2, '3135', 'CC-235', 'Has your organisation been removed from the Register of Training Organisations (RoTO) in the last 3 years? '),
					(3, 2, '3100', 'CC-235-1', 'Give us more information'),
					(3, 2, '3140', 'CC-24', 'Has your organisation had funding removed from any education bodies in the last 3 years?'),
					(3, 2, '3100', 'CC-24-1', 'Give us more information'),
					(3, 2, '3150', 'CC-25', 'Has your organisation been removed from any professional or trade registers in the last 3 years?'),
					(3, 2, '3100', 'CC-25-1', 'Give us more information'),
					(3, 2, '3160', 'CC-26', 'Has your organisation been involuntarily withdrawn from Initial Teacher Training accreditation in the last 3 years?'),
					(3, 2, '3100', 'CC-26-1', 'Give us more information'),
					(3, 2, '3170', 'CC-27', 'Has your organisation been removed from any charity register?'),
					(3, 2, '3100', 'CC-27-1', 'Give us more information'),
					(3, 2, '3180', 'CC-28', 'Has your organisation been investigated due to safeguarding issues in the last 3 months?'),
					(3, 2, '3100', 'CC-28-1', 'Give us more information'),
					(3, 2, '3190', 'CC-29', 'Is your organisation currently, or has within the last 5 years been, subject to an investigation by the ESFA or other public body or regulator?'),
					(3, 2, '3100', 'CC-29-1', 'Give us more information'),
					(3, 2, '3199', 'CC-30', 'Has your organisation been subject to insolvency or winding up proceedings in the last 3 years?'),
					(3, 2, '3100', 'CC-30-1', 'Give us more information'),
					(3, 4, '3300', 'CC-40', 'Does anyone who''s in control of your organisation have any unspent criminal convictions?'),
					(3, 4, '3100', 'CC-40-1', 'Give us more information'),
					(3, 4, '3301', 'CC-41', 'Do you have any unspent criminal convictions?'),
					(3, 4, '3100', 'CC-41-1', 'Give us more information'),
					(3, 4, '3310', 'CC-50', 'Has anyone who''s in control of your organisation failed to pay back funds in the last 3 years?'),
					(3, 4, '3100', 'CC-50-1', 'Give us more information'),
					(3, 4, '3311', 'CC-51', 'Have you failed to pay back funds in the last 3 years?'),
					(3, 4, '3100', 'CC-51-1', 'Give us more information'),
					(3, 4, '3320', 'CC-60', 'Has anyone who''s in control of your organisation been investigated for fraud or irregularities in the last 3 years?'),
					(3, 4, '3100', 'CC-60-1', 'Give us more information'),
					(3, 4, '3321', 'CC-61', 'Have you been investigated for fraud or irregularities in the last 3 years?'),
					(3, 4, '3100', 'CC-61-1', 'Give us more information'),
					(3, 4, '3330', 'CC-70', 'Does anyone who''s in control of your organisation have any ongoing investigations for fraud or irregularities?'),
					(3, 4, '3100', 'CC-70-1', 'Give us more information'),
					(3, 4, '3331', 'CC-71', 'Do you have any ongoing investigations for fraud or irregularities?'),
					(3, 4, '3100', 'CC-71-1', 'Give us more information'),
					(3, 4, '3340', 'CC-80', 'Has anyone who''s in control of your organisation had a contract terminated by a public body in the last 3 years?'),
					(3, 4, '3100', 'CC-80-1', 'Give us more information'),
					(3, 4, '3341', 'CC-81', 'Have you had a contract terminated by a public body in the last 3 years?'),
					(3, 4, '3100', 'CC-81-1', 'Give us more information'),
					(3, 4, '3350', 'CC-90', 'Has anyone who''s in control of your organisation withdrawn from a contract with a public body in the last 3 years?'),
					(3, 4, '3100', 'CC-90-1', 'Give us more information'),
					(3, 4, '3351', 'CC-91', 'Have you withdrawn from a contract with a public body in the last 3 years?'),
					(3, 4, '3100', 'CC-91-1', 'Give us more information'),
					(3, 4, '3360', 'CC-100', 'Has anyone who''s in control of your organisation breached tax payments or social security contributions in the last 3 years?'),
					(3, 4, '3100', 'CC-100-1', 'Give us more information'),
					(3, 4, '3361', 'CC-101', 'Have you breached tax payments or social security contributions in the last 3 years?'),
					(3, 4, '3100', 'CC-101-1', 'Give us more information'),
					(3, 4, '3370', 'CC-110', 'Is anyone who''s in control of your organisation on the Register of Removed Trustees?'),
					(3, 4, '3100', 'CC-110-1', 'Give us more information'),
					(3, 4, '3371', 'CC-111', 'Are you on the Register of Removed Trustees?'),
					(3, 4, '3100', 'CC-111-1', 'Give us more information'),
					(3, 4, '3380', 'CC-120', 'Has anyone who''s in control of your organisation or any of its partner organisations been made bankrupt in the last 3 years?'),
					(3, 4, '3100', 'CC-120-1', 'Give us more information'),
					(3, 4, '3381', 'CC-121', 'Have you been made bankrupt in the last 3 years?'),
					(3, 4, '3100', 'CC-121-1', 'Give us more information'),
					(3, 4, '3390', 'CC-130', 'Has anyone who''s in control of your organisation, or any of its partner organisations, been subject to a prohibition order from the Teaching Regulation Agency on behalf of the Secretary of State for Education?'),
					(3, 4, '3100', 'CC-130-1', 'Give us more information'),
					(3, 4, '3391', 'CC-131', 'Have you been subject to a prohibition order from the Teaching Regulation Agency on behalf of the Secretary of State for Education?'),
					(3, 4, '3100', 'CC-131-1', 'Give us more information'),
					(3, 4, '3395', 'CC-135', 'Has anyone who''s in control of your organisation, or any of its partner organisations, been subject to a ban from management or governance of schools?'),
					(3, 4, '3100', 'CC-135-1', 'Give us more information'),
					(3, 4, '3396', 'CC-136', 'Have you been subject to a ban from  management or governance of schools?'),
					(3, 4, '3100', 'CC-136-1', 'Give us more information'),
					(4, 2, '4010', 'PYA-20', 'Upload your organisation''s continuity plan for apprenticeship training'),
					(4, 3, '4020', 'PYA-30', 'Upload your organisation''s equality and diversity policy'),
					(4, 4, '4030', 'PYA-40', 'Upload your organisation''s safeguarding policy'),
					(4, 4, '4035', 'PYA-45', 'Full name'),
					(4, 4, '4035', 'PYA-46', 'Email'),
					(4, 4, '4035', 'PYA-47', 'Contact number'),
					(4, 4, '4037', 'PYA-48', 'SafeguardingPolicyIncludesPreventDutyPolicy'),
					(4, 4, '4038', 'PYA-49', 'PreventDutyPolicy'),
					(4, 5, '4040', 'PYA-50', 'Upload your organisation''s health and safety policy'),
					(4, 5, '4045', 'PYA-55', 'Full name'),
					(4, 5, '4045', 'PYA-56', 'Email'),
					(4, 5, '4045', 'PYA-57', 'Contact number'),
					(4, 6, '4050', 'PYA-60', 'When acting as a subcontractor, will your organisation follow its lead provider''s policies and plans?'),
					(5, 2, '5100', 'RTE-20', 'Has your organisation engaged with employers to deliver apprenticeship training to their employees?'),
					(5, 2, '5100', 'RTE-20-1', 'Who have you engaged with?'),
					(5, 2, '5110', 'RTE-21', 'How will your organisation manage its relationship with employers?'),
					(5, 2, '5120', 'RTE-22-1', 'Full name'),
					(5, 2, '5120', 'RTE-22-2', 'Email'),
					(5, 2, '5120', 'RTE-22-3', 'Contact number'),
					(5, 2, '5130', 'RTE-23', 'How will your organisation promote apprenticeships to employers?'),
					(5, 3, '5200', 'RTE-30', 'Upload your organisation''s complaints policy'),
					(5, 3, '5210', 'RTE-31', 'Enter the website link for your organisation''s complaints policy'),
					(5, 4, '5300', 'RTE-40', 'Upload your organisation''s contract for services template with employers'),
					(5, 5, '5400', 'RTE-50', 'Upload your organisation''s commitment statement template'),
					(5, 6, '5500', 'RTE-60', 'What is your organisation''s process for initial assessments to recognise prior learning?'),
					(5, 6, '5510', 'RTE-61', 'What is your organisation''s process to assess English and maths qualifications for apprentices?'),
					(5, 7, '5550', 'RTE-65', 'How will you deliver the assessments in English and maths?'),
					(5, 7, '5560', 'RTE-66', 'Where will you deliver the assessments in English and maths?'),
					(5, 7, '5570', 'RTE-67', 'How will you continue to deliver English and maths training and assessments if there''s a significant event?'),
					(5, 8, '5600', 'RTE-70', 'Does your organisation expect to use subcontractors in the first 12 months of joining RoATP?'),
					(5, 8, '5610', 'RTE-71', 'How will your organisation carry out due diligence on its subcontractors?'),
					(6, 2, '6201', 'PAT-21', 'What type of apprenticeship training will your organisation offer?'),
					(6, 2, '6202', 'PAT-22', 'What type of apprenticeship training will your organisation offer?'),
					(6, 2, '6203', 'PAT-23', 'What type of apprenticeship training will your organisation offer?'),
					(6, 2, '6230', 'PAT-30', 'Tell us how your organisation is ready to deliver training in apprenticeship standards'),
					(6, 2, '6250', 'PAT-50', 'Does your organisation have a plan to transition from apprenticeship frameworks to apprenticeship standards?'),
					(6, 2, '6252', 'PAT-52', 'How will your organisation transition from apprenticeship frameworks to apprenticeship standards?'),
					(6, 2, '6253', 'PAT-53', 'How will your organisation transition from apprenticeship frameworks to apprenticeship standards?'),
					(6, 2, '6254', 'PAT-54', 'Why will your organisation only deliver apprenticeship frameworks?'),
					(6, 2, '6260', 'PAT-60', 'Does your organisation have a plan to transition from apprenticeship frameworks to apprenticeship standards?'),
					(6, 2, '6262', 'PAT-62', 'How will your organisation transition from apprenticeship frameworks to apprenticeship standards?'),
					(6, 2, '6264', 'PAT-64', 'Why will your organisation only deliver apprenticeship frameworks?'),
					(6, 2, '6270', 'PAT-70', 'How will your organisation engage with end-point assessment organisations (EPAOs)?'),
					(6, 2, '6280', 'PAT-80', 'How will your organisation plan to engage and work with awarding bodies?'),
					(6, 3, '6300', 'PAT-630', 'How will your organisation train its apprentices?'),
					(6, 4, '6400', 'PAT-640', 'How will your organisation ensure apprentices are supported during their apprenticeship training?'),
					(6, 4, '6405', 'PAT-6405', 'How will your organisation ensure apprentices are supported during their apprenticeship training?'),
					(6, 4, '6410', 'PAT-641', 'How will your organisation support its apprentices?'),
					(6, 4, '6420', 'PAT-642', 'What other ways will your organisation use to support its apprentices?'),
					(6, 5, '6500', 'PAT-650', 'How many starts does your organisation forecast in the first 12 months of joining the RoATP?'),
					(6, 5, '6510', 'PAT-651', 'When will your organisation be ready to deliver training against this forecast?'),
					(6, 5, '6520', 'PAT-652', 'Will your organisation recruit new staff to deliver training against these forecasts?'),
					(6, 5, '6530', 'PAT-653', 'What is the typical ratio of the staff who deliver training to the apprentices?'),
					(6, 5, '6540', 'PAT-654', 'How does your proposed staff to learner ratio offer quality support to your apprentices?'),
					(6, 6, '6600', 'PAT-660', 'What teaching methods will your organisation use to deliver 20% off the job training?'),
					(6, 6, '6610', 'PAT-661', 'How will your organisation ensure 20% off the job training is relevant to the specific apprenticeship being delivered?'),
					(6, 7, '6700', 'PAT-670', 'Building and Street'),
					(6, 7, '6700', 'PAT-671', 'Town or City'),
					(6, 7, '6700', 'PAT-672', 'County'),
					(6, 7, '6700', 'PAT-673', 'Postcode'),
					(7, 2, '7100', 'DAT-10-1', 'Full name'),
					(7, 2, '7100', 'DAT-10-2', 'Email'),
					(7, 2, '7100', 'DAT-10-3', 'Contact number'),
					(7, 2, '7100', 'DAT-10-4', 'Is this person part of any other organisations?'),
					(7, 3, '7200', 'DAT-720', 'Confirm management hierarchy'),
					(7, 4, '7300', 'DAT-40', 'Upload your management hierarchy''s expectations for quality and high standards in apprenticeship training'),
					(7, 4, '7305', 'DAT-7305', 'Tell us how these expectations for quality and high standards in apprenticeship training are monitored and evaluated'),
					(7, 4, '7310', 'DAT-41-1', 'Full name'),
					(7, 4, '7310', 'DAT-41-2', 'Email'),
					(7, 4, '7310', 'DAT-41-3', 'Contact number'),
					(7, 4, '7320', 'DAT-42', 'How are these expectations for quality and high standards in apprenticeship training communicated to employees?'),
					(7, 5, '7500', 'DAT-750', 'Does your organisation have a team responsible for developing and delivering training?'),
					(7, 5, '7510', 'DAT-751', 'Does your organisation have someone responsible for developing and delivering training?'),
					(7, 5, '7520', 'DAT-752', 'Does your organisation have someone responsible for developing and delivering training?'),
					(7, 5, '7530', 'DAT-753', 'Who has the team worked with to develop and deliver training?'),
					(7, 5, '7540', 'DAT-754-1', 'Full name'),
					(7, 5, '7540', 'DAT-754-2', 'How much experience do they have in developing and delivering training?'),
					(7, 5, '7560', 'DAT-756', 'Who has this person worked with to develop and deliver training?'),
					(7, 5, '7570', 'DAT-757', 'How has the team worked with other organisations to develop and deliver training?'),
					(7, 5, '7590', 'DAT-759-1', 'Full name'),
					(7, 5, '7590', 'DAT-759-2', 'Do they have at least 3 months experience in developing and delivering training?'),
					(7, 5, '7591', 'DAT-7591', 'How has the team worked with other organisations and employers to develop and deliver training?'),
					(7, 5, '7592', 'DAT-7592', 'How has the team worked with employers to develop and deliver training?'),
					(7, 5, '7593', 'DAT-7593', 'How has this person worked with other organisations to develop and deliver training?'),
					(7, 5, '7594', 'DAT-7594', 'How has this person worked with other organisations and employers to develop and deliver training?'),
					(7, 5, '7595', 'DAT-7595', 'How has this person worked with employers to develop and deliver training?'),
					(7, 6, '7600', 'DAT-7600', 'What sectors will your organisation deliver apprenticeship training in?'),
					(7, 6, '7610', 'DAT-7610-1', 'First name'),
					(7, 6, '7610', 'DAT-7610-2', 'Last name'),
					(7, 6, '7610', 'DAT-7610-3', 'Job role'),
					(7, 6, '7610', 'DAT-7610-4', 'Time in role (years and months)'),
					(7, 6, '7610', 'DAT-7610-5', 'Is this person part of any other organisations?'),
					(7, 6, '7610', 'DAT-7610-6', 'Enter the names of all these organisations'),
					(7, 6, '7610', 'DAT-7610-7', 'Date of birth'),
					(7, 6, '7610', 'DAT-7610-8', 'Email'),
					(7, 6, '7610', 'DAT-7610-9', 'Contact number'),
					(7, 6, '7610A', 'DAT-7610A-1', 'How many starts does your organisation forecast in the ''Agriculture, environmental and animal care'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7610AA', 'DAT-7610AA-1', 'What standards do you intend to deliver within the ''Agriculture, environmental and animal care'' sector?'),
					(7, 6, '7610B', 'DAT-7610B-1', 'How many employees will deliver training in the ''Agriculture, environmental and animal care'' sector?'),
					(7, 6, '7611', 'DAT-76111', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7611', 'DAT-76112', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7611', 'DAT-76113', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7611', 'DAT-76114', 'Do they have sector or trade body memberships?'),
					(7, 6, '7612', 'DAT-76121', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7613', 'DAT-76131', 'How have they delivered training to apprentices?'),
					(7, 6, '7613', 'DAT-76132', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7613', 'DAT-76133', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7615', 'DAT-7615-1', 'First name'),
					(7, 6, '7615', 'DAT-7615-2', 'Last name'),
					(7, 6, '7615', 'DAT-7615-3', 'Job role'),
					(7, 6, '7615', 'DAT-7615-4', 'Time in role (years and months)'),
					(7, 6, '7615', 'DAT-7615-5', 'Is this person part of any other organisations?'),
					(7, 6, '7615', 'DAT-7615-6', 'Enter the names of all these organisations'),
					(7, 6, '7615', 'DAT-7615-7', 'Date of birth'),
					(7, 6, '7615', 'DAT-7615-8', 'Email'),
					(7, 6, '7615', 'DAT-7615-9', 'Contact number'),
					(7, 6, '7615A', 'DAT-7615A-1', 'How many starts does your organisation forecast in the ''Business and administration'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7615AA', 'DAT-7615AA-1', 'What standards do you intend to deliver within the ''Business and administration'' sector?'),
					(7, 6, '7615B', 'DAT-7615B-1', 'How many employees will deliver training in the ''Business and administration'' sector?'),
					(7, 6, '7616', 'DAT-76161', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7616', 'DAT-76162', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7616', 'DAT-76163', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7616', 'DAT-76164', 'Do they have sector or trade body memberships?'),
					(7, 6, '7617', 'DAT-76171', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7618', 'DAT-76181', 'How have they delivered training to apprentices?'),
					(7, 6, '7618', 'DAT-76182', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7618', 'DAT-76183', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7620', 'DAT-7620-1', 'First name'),
					(7, 6, '7620', 'DAT-7620-2', 'Last name'),
					(7, 6, '7620', 'DAT-7620-3', 'Job role'),
					(7, 6, '7620', 'DAT-7620-4', 'Time in role (years and months)'),
					(7, 6, '7620', 'DAT-7620-5', 'Is this person part of any other organisations?'),
					(7, 6, '7620', 'DAT-7620-6', 'Enter the names of all these organisations'),
					(7, 6, '7620', 'DAT-7620-7', 'Date of birth'),
					(7, 6, '7620', 'DAT-7620-8', 'Email'),
					(7, 6, '7620', 'DAT-7620-9', 'Contact number'),
					(7, 6, '7620A', 'DAT-7620A-1', 'How many starts does your organisation forecast in the ''Care services'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7620AA', 'DAT-7620AA-1', 'What standards do you intend to deliver within the ''Care services'' sector?'),
					(7, 6, '7620B', 'DAT-7620B-1', 'How many employees will deliver training in the ''Care services'' sector?'),
					(7, 6, '7621', 'DAT-76211', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7621', 'DAT-76212', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7621', 'DAT-76213', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7621', 'DAT-76214', 'Do they have sector or trade body memberships?'),
					(7, 6, '7622', 'DAT-76221', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7623', 'DAT-76231', 'How have they delivered training to apprentices?'),
					(7, 6, '7623', 'DAT-76232', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7623', 'DAT-76233', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7625', 'DAT-7625-1', 'First name'),
					(7, 6, '7625', 'DAT-7625-2', 'Last name'),
					(7, 6, '7625', 'DAT-7625-3', 'Job role'),
					(7, 6, '7625', 'DAT-7625-4', 'Time in role (years and months)'),
					(7, 6, '7625', 'DAT-7625-5', 'Is this person part of any other organisations?'),
					(7, 6, '7625', 'DAT-7625-6', 'Enter the names of all these organisations'),
					(7, 6, '7625', 'DAT-7625-7', 'Date of birth'),
					(7, 6, '7625', 'DAT-7625-8', 'Email'),
					(7, 6, '7625', 'DAT-7625-9', 'Contact number'),
					(7, 6, '7625A', 'DAT-7625A-1', 'How many starts does your organisation forecast in the ''Catering and hospitality'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7625AA', 'DAT-7625AA-1', 'What standards do you intend to deliver within the ''Catering and hospitality'' sector?'),
					(7, 6, '7625B', 'DAT-7625B-1', 'How many employees will deliver training in the ''Catering and hospitality'' sector?'),
					(7, 6, '7626', 'DAT-76261', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7626', 'DAT-76262', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7626', 'DAT-76263', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7626', 'DAT-76264', 'Do they have sector or trade body memberships?'),
					(7, 6, '7627', 'DAT-76271', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7628', 'DAT-76281', 'How have they delivered training to apprentices?'),
					(7, 6, '7628', 'DAT-76282', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7628', 'DAT-76283', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7630', 'DAT-7630-1', 'First name'),
					(7, 6, '7630', 'DAT-7630-2', 'Last name'),
					(7, 6, '7630', 'DAT-7630-3', 'Job role'),
					(7, 6, '7630', 'DAT-7630-4', 'Time in role (years and months)'),
					(7, 6, '7630', 'DAT-7630-5', 'Is this person part of any other organisations?'),
					(7, 6, '7630', 'DAT-7630-6', 'Enter the names of all these organisations'),
					(7, 6, '7630', 'DAT-7630-7', 'Date of birth'),
					(7, 6, '7630', 'DAT-7630-8', 'Email'),
					(7, 6, '7630', 'DAT-7630-9', 'Contact number'),
					(7, 6, '7630A', 'DAT-7630A-1', 'How many starts does your organisation forecast in the ''Construction'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7630AA', 'DAT-7630AA-1', 'What standards do you intend to deliver within the ''Construction'' sector?'),
					(7, 6, '7630B', 'DAT-7630B-1', 'How many employees will deliver training in the ''Construction'' sector?'),
					(7, 6, '7631', 'DAT-76311', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7631', 'DAT-76312', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7631', 'DAT-76313', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7631', 'DAT-76314', 'Do they have sector or trade body memberships?'),
					(7, 6, '7632', 'DAT-76321', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7633', 'DAT-76331', 'How have they delivered training to apprentices?'),
					(7, 6, '7633', 'DAT-76332', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7633', 'DAT-76333', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7635', 'DAT-7635-1', 'First name'),
					(7, 6, '7635', 'DAT-7635-2', 'Last name'),
					(7, 6, '7635', 'DAT-7635-3', 'Job role'),
					(7, 6, '7635', 'DAT-7635-4', 'Time in role (years and months)'),
					(7, 6, '7635', 'DAT-7635-5', 'Is this person part of any other organisations?'),
					(7, 6, '7635', 'DAT-7635-6', 'Enter the names of all these organisations'),
					(7, 6, '7635', 'DAT-7635-7', 'Date of birth'),
					(7, 6, '7635', 'DAT-7635-8', 'Email'),
					(7, 6, '7635', 'DAT-7635-9', 'Contact number'),
					(7, 6, '7635A', 'DAT-7635A-1', 'How many starts does your organisation forecast in the ''Creative and design'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7635AA', 'DAT-7635AA-1', 'What standards do you intend to deliver within the ''Creative and design'' sector?'),
					(7, 6, '7635B', 'DAT-7635B-1', 'How many employees will deliver training in the ''Creative and design'' sector?'),
					(7, 6, '7636', 'DAT-76361', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7636', 'DAT-76362', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7636', 'DAT-76363', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7636', 'DAT-76364', 'Do they have sector or trade body memberships?'),
					(7, 6, '7637', 'DAT-76371', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7638', 'DAT-76381', 'How have they delivered training to apprentices?'),
					(7, 6, '7638', 'DAT-76382', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7638', 'DAT-76383', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7640', 'DAT-7640-1', 'First name'),
					(7, 6, '7640', 'DAT-7640-2', 'Last name'),
					(7, 6, '7640', 'DAT-7640-3', 'Job role'),
					(7, 6, '7640', 'DAT-7640-4', 'Time in role (years and months)'),
					(7, 6, '7640', 'DAT-7640-5', 'Is this person part of any other organisations?'),
					(7, 6, '7640', 'DAT-7640-6', 'Enter the names of all these organisations'),
					(7, 6, '7640', 'DAT-7640-7', 'Date of birth'),
					(7, 6, '7640', 'DAT-7640-8', 'Email'),
					(7, 6, '7640', 'DAT-7640-9', 'Contact number'),
					(7, 6, '7640A', 'DAT-7640A-1', 'How many starts does your organisation forecast in the ''Digital'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7640AA', 'DAT-7640AA-1', 'What standards do you intend to deliver within the ''Digital'' sector?'),
					(7, 6, '7640B', 'DAT-7640B-1', 'How many employees will deliver training in the ''Digital'' sector?'),
					(7, 6, '7641', 'DAT-76411', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7641', 'DAT-76412', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7641', 'DAT-76413', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7641', 'DAT-76414', 'Do they have sector or trade body memberships?'),
					(7, 6, '7642', 'DAT-76421', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7643', 'DAT-76431', 'How have they delivered training to apprentices?'),
					(7, 6, '7643', 'DAT-76432', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7643', 'DAT-76433', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7645', 'DAT-7645-1', 'First name'),
					(7, 6, '7645', 'DAT-7645-2', 'Last name'),
					(7, 6, '7645', 'DAT-7645-3', 'Job role'),
					(7, 6, '7645', 'DAT-7645-4', 'Time in role (years and months)'),
					(7, 6, '7645', 'DAT-7645-5', 'Is this person part of any other organisations?'),
					(7, 6, '7645', 'DAT-7645-6', 'Enter the names of all these organisations'),
					(7, 6, '7645', 'DAT-7645-7', 'Date of birth'),
					(7, 6, '7645', 'DAT-7645-8', 'Email'),
					(7, 6, '7645', 'DAT-7645-9', 'Contact number'),
					(7, 6, '7645A', 'DAT-7645A-1', 'How many starts does your organisation forecast in the ''Education and childcare'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7645AA', 'DAT-7645AA-1', 'What standards do you intend to deliver within the ''Education and childcare'' sector?'),
					(7, 6, '7645B', 'DAT-7645B-1', 'How many employees will deliver training in the ''Education and childcare'' sector?'),
					(7, 6, '7646', 'DAT-76461', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7646', 'DAT-76462', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7646', 'DAT-76463', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7646', 'DAT-76464', 'Do they have sector or trade body memberships?'),
					(7, 6, '7647', 'DAT-76471', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7648', 'DAT-76481', 'How have they delivered training to apprentices?'),
					(7, 6, '7648', 'DAT-76482', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7648', 'DAT-76483', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7650', 'DAT-7650-1', 'First name'),
					(7, 6, '7650', 'DAT-7650-2', 'Last name'),
					(7, 6, '7650', 'DAT-7650-3', 'Job role'),
					(7, 6, '7650', 'DAT-7650-4', 'Time in role (years and months)'),
					(7, 6, '7650', 'DAT-7650-5', 'Is this person part of any other organisations?'),
					(7, 6, '7650', 'DAT-7650-6', 'Enter the names of all these organisations'),
					(7, 6, '7650', 'DAT-7650-7', 'Date of birth'),
					(7, 6, '7650', 'DAT-7650-8', 'Email'),
					(7, 6, '7650', 'DAT-7650-9', 'Contact number'),
					(7, 6, '7650A', 'DAT-7650A-1', 'How many starts does your organisation forecast in the ''Engineering and manufacturing'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7650AA', 'DAT-7650AA-1', 'What standards do you intend to deliver within the ''Engineering and manufacturing'' sector?'),
					(7, 6, '7650B', 'DAT-7650B-1', 'How many employees will deliver training in the ''Engineering and manufacturing'' sector?'),
					(7, 6, '7651', 'DAT-76511', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7651', 'DAT-76512', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7651', 'DAT-76513', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7651', 'DAT-76514', 'Do they have sector or trade body memberships?'),
					(7, 6, '7652', 'DAT-76521', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7653', 'DAT-76531', 'How have they delivered training to apprentices?'),
					(7, 6, '7653', 'DAT-76532', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7653', 'DAT-76533', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7655', 'DAT-7655-1', 'First name'),
					(7, 6, '7655', 'DAT-7655-2', 'Last name'),
					(7, 6, '7655', 'DAT-7655-3', 'Job role'),
					(7, 6, '7655', 'DAT-7655-4', 'Time in role (years and months)'),
					(7, 6, '7655', 'DAT-7655-5', 'Is this person part of any other organisations?'),
					(7, 6, '7655', 'DAT-7655-6', 'Enter the names of all these organisations'),
					(7, 6, '7655', 'DAT-7655-7', 'Date of birth'),
					(7, 6, '7655', 'DAT-7655-8', 'Email'),
					(7, 6, '7655', 'DAT-7655-9', 'Contact number'),
					(7, 6, '7655A', 'DAT-7655A-1', 'How many starts does your organisation forecast in the ''Hair and Beauty'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7655AA', 'DAT-7655AA-1', 'What standards do you intend to deliver within the ''Hair and Beauty'' sector?'),
					(7, 6, '7655B', 'DAT-7655B-1', 'How many employees will deliver training in the ''Hair and Beauty'' sector?'),
					(7, 6, '7656', 'DAT-76561', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7656', 'DAT-76562', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7656', 'DAT-76563', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7656', 'DAT-76564', 'Do they have sector or trade body memberships?'),
					(7, 6, '7657', 'DAT-76571', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7658', 'DAT-76581', 'How have they delivered training to apprentices?'),
					(7, 6, '7658', 'DAT-76582', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7658', 'DAT-76583', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7660', 'DAT-7660-1', 'First name'),
					(7, 6, '7660', 'DAT-7660-2', 'Last name'),
					(7, 6, '7660', 'DAT-7660-3', 'Job role'),
					(7, 6, '7660', 'DAT-7660-4', 'Time in role (years and months)'),
					(7, 6, '7660', 'DAT-7660-5', 'Is this person part of any other organisations?'),
					(7, 6, '7660', 'DAT-7660-6', 'Enter the names of all these organisations'),
					(7, 6, '7660', 'DAT-7660-7', 'Date of birth'),
					(7, 6, '7660', 'DAT-7660-8', 'Email'),
					(7, 6, '7660', 'DAT-7660-9', 'Contact number'),
					(7, 6, '7660A', 'DAT-7660A-1', 'How many starts does your organisation forecast in the ''Health and science'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7660AA', 'DAT-7660AA-1', 'What standards do you intend to deliver within the ''Health and science'' sector?'),
					(7, 6, '7660B', 'DAT-7660B-1', 'How many employees will deliver training in the ''Health and science'' sector?'),
					(7, 6, '7661', 'DAT-76611', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7661', 'DAT-76612', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7661', 'DAT-76613', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7661', 'DAT-76614', 'Do they have sector or trade body memberships?'),
					(7, 6, '7662', 'DAT-76621', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7663', 'DAT-76631', 'How have they delivered training to apprentices?'),
					(7, 6, '7663', 'DAT-76632', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7663', 'DAT-76633', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7665', 'DAT-7665-1', 'First name'),
					(7, 6, '7665', 'DAT-7665-2', 'Last name'),
					(7, 6, '7665', 'DAT-7665-3', 'Job role'),
					(7, 6, '7665', 'DAT-7665-4', 'Time in role (years and months)'),
					(7, 6, '7665', 'DAT-7665-5', 'Is this person part of any other organisations?'),
					(7, 6, '7665', 'DAT-7665-6', 'Enter the names of all these organisations'),
					(7, 6, '7665', 'DAT-7665-7', 'Date of birth'),
					(7, 6, '7665', 'DAT-7665-8', 'Email'),
					(7, 6, '7665', 'DAT-7665-9', 'Contact number'),
					(7, 6, '7665A', 'DAT-7665A-1', 'How many starts does your organisation forecast in the ''Legal, finance and accounting'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7665AA', 'DAT-7665AA-1', 'What standards do you intend to deliver within the ''Legal, finance and accounting'' sector?'),
					(7, 6, '7665B', 'DAT-7665B-1', 'How many employees will deliver training in the ''Legal, finance and accounting'' sector?'),
					(7, 6, '7666', 'DAT-76661', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7666', 'DAT-76662', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7666', 'DAT-76663', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7666', 'DAT-76664', 'Do they have sector or trade body memberships?'),
					(7, 6, '7667', 'DAT-76671', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7668', 'DAT-76681', 'How have they delivered training to apprentices?'),
					(7, 6, '7668', 'DAT-76682', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7668', 'DAT-76683', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7670', 'DAT-7670-1', 'First name'),
					(7, 6, '7670', 'DAT-7670-2', 'Last name'),
					(7, 6, '7670', 'DAT-7670-3', 'Job role'),
					(7, 6, '7670', 'DAT-7670-4', 'Time in role (years and months)'),
					(7, 6, '7670', 'DAT-7670-5', 'Is this person part of any other organisations?'),
					(7, 6, '7670', 'DAT-7670-6', 'Enter the names of all these organisations'),
					(7, 6, '7670', 'DAT-7670-7', 'Date of birth'),
					(7, 6, '7670', 'DAT-7670-8', 'Email'),
					(7, 6, '7670', 'DAT-7670-9', 'Contact number'),
					(7, 6, '7670A', 'DAT-7670A-1', 'How many starts does your organisation forecast in the ''Protective services'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7670AA', 'DAT-7670AA-1', 'What standards do you intend to deliver within the ''Protective services'' sector?'),
					(7, 6, '7670B', 'DAT-7670B-1', 'How many employees will deliver training in the ''Protective services'' sector?'),
					(7, 6, '7671', 'DAT-76711', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7671', 'DAT-76712', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7671', 'DAT-76713', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7671', 'DAT-76714', 'Do they have sector or trade body memberships?'),
					(7, 6, '7672', 'DAT-76721', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7673', 'DAT-76731', 'How have they delivered training to apprentices?'),
					(7, 6, '7673', 'DAT-76732', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7673', 'DAT-76733', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7675', 'DAT-7675-1', 'First name'),
					(7, 6, '7675', 'DAT-7675-2', 'Last name'),
					(7, 6, '7675', 'DAT-7675-3', 'Job role'),
					(7, 6, '7675', 'DAT-7675-4', 'Time in role (years and months)'),
					(7, 6, '7675', 'DAT-7675-5', 'Is this person part of any other organisations?'),
					(7, 6, '7675', 'DAT-7675-6', 'Enter the names of all these organisations'),
					(7, 6, '7675', 'DAT-7675-7', 'Date of birth'),
					(7, 6, '7675', 'DAT-7675-8', 'Email'),
					(7, 6, '7675', 'DAT-7675-9', 'Contact number'),
					(7, 6, '7675A', 'DAT-7675A-1', 'How many starts does your organisation forecast in the ''Sales, marketing and procurement'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7675AA', 'DAT-7675AA-1', 'What standards do you intend to deliver within the ''Sales, marketing and procurement'' sector?'),
					(7, 6, '7675B', 'DAT-7675B-1', 'How many employees will deliver training in the ''Sales, marketing and procurement'' sector?'),
					(7, 6, '7676', 'DAT-76761', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7676', 'DAT-76762', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7676', 'DAT-76763', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7676', 'DAT-76764', 'Do they have sector or trade body memberships?'),
					(7, 6, '7677', 'DAT-76771', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7678', 'DAT-76781', 'How have they delivered training to apprentices?'),
					(7, 6, '7678', 'DAT-76782', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7678', 'DAT-76783', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7680', 'DAT-7680-1', 'First name'),
					(7, 6, '7680', 'DAT-7680-2', 'Last name'),
					(7, 6, '7680', 'DAT-7680-3', 'Job role'),
					(7, 6, '7680', 'DAT-7680-4', 'Time in role (years and months)'),
					(7, 6, '7680', 'DAT-7680-5', 'Is this person part of any other organisations?'),
					(7, 6, '7680', 'DAT-7680-6', 'Enter the names of all these organisations'),
					(7, 6, '7680', 'DAT-7680-7', 'Date of birth'),
					(7, 6, '7680', 'DAT-7680-8', 'Email'),
					(7, 6, '7680', 'DAT-7680-9', 'Contact number'),
					(7, 6, '7680A', 'DAT-7680A-1', 'How many starts does your organisation forecast in the ''Transport and logistics'' sector in the first 12 months of joining the RoATP?'),
					(7, 6, '7680AA', 'DAT-7680AA-1', 'What standards do you intend to deliver within the ''Transport and logistics'' sector?'),
					(7, 6, '7680B', 'DAT-7680B-1', 'How many employees will deliver training in the ''Transport and logistics'' sector?'),
					(7, 6, '7681', 'DAT-76811', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7681', 'DAT-76812', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7681', 'DAT-76813', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7681', 'DAT-76814', 'Do they have sector or trade body memberships?'),
					(7, 6, '7682', 'DAT-76821', 'What type of apprenticeship training have they delivered? '),
					(7, 6, '7683', 'DAT-76831', 'How have they delivered training to apprentices?'),
					(7, 6, '7683', 'DAT-76832', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7683', 'DAT-76833', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 7, '7700', 'DAT-770', 'Upload your organisation''s policy for professional development of employees'),
					(7, 7, '7710', 'DAT-771', 'Give an example of how your organisation used this policy to improve employee sector expertise'),
					(7, 7, '7720', 'DAT-772', 'Give an example of how your organisation used this policy to maintain employee teaching and training knowledge'),
					(8, 2, '8100', 'EAT-20', 'What is your organisation''s process for evaluating the quality of training delivered?'),
					(8, 2, '8110', 'EAT-21', 'How has your organisation made improvements using its process for evaluating the quality of training delivered?'),
					(8, 3, '8200', 'EAT-30', 'Does your organisation''s process for evaluating the quality of training delivered include apprenticeship training?'),
					(8, 3, '8210', 'EAT-40', 'How will your organisation evaluate the quality of apprenticeship training?'),
					(8, 3, '8220', 'EAT-41', 'How will your organisation evaluate the quality of apprenticeship training?'),
					(8, 3, '8230', 'EAT-50', 'How will your organisation review its process for evaluating the quality of training delivered?'),
					(8, 4, '8300', 'EAT-60', 'Does your organisation have systems and processes in place to collect apprenticeship data?'),
					(8, 4, '8310', 'EAT-70', 'Does your organisation have the resources to submit Individualised Learner Record (ILR) data?'),
					(8, 4, '8320', 'EAT-80', 'Full name'),
					(8, 4, '8320', 'EAT-81', 'Email'),
					(8, 4, '8320', 'EAT-82', 'Contact number'),
					(9, 1, '9000', 'FIN-10', 'Do you have permission from everyone named in this application to use their details?'),
					(9, 1, '9010', 'FIN-20', 'Have you checked with everyone named in this application that the details provided for them are accurate?'),
					(9, 1, '9020', 'FIN-30', 'Do you have permission from your organisation to submit this application?'),
					(9, 2, '9100', 'FIN-40', 'Do you understand that your organisation must develop and deliver apprenticeship training in line with the Institute for Apprenticeships and Technical Education''s ''quality statement''?'),
					(9, 3, '9200', 'FIN-50', 'Do you understand that your organisation will not join the RoATP until it completes all post application tasks?');





					DELETE FROM [Mtd].[RP_LookupSectionTitles] 

					/*  Insert into [Mtd].[RP_LookupSectionTitles] */
					INSERT INTO [Mtd].[RP_LookupSectionTitles] 
					([SequenceNumber],[SectionNumber],[Title]) 
					VALUES
						(0, 1, 'Preamble'),
						(1, 1, 'Introduction and what you''ll need'),
						(1, 2, 'Organisation information'),
						(1, 3, 'Confirm who''s in control'),
						(1, 4, 'Describe your organisation'),
						(1, 5, 'Experience and accreditation'),
						(2, 1, 'Introduction and what you''ll need'),
						(2, 2, 'Your organisation''s financial evidence'),
						(2, 3, 'Your UK ultimate parent company''s financial evidence'),
						(3, 1, 'Introduction and what you''ll need'),
						(3, 2, 'Checks on your organisation'),
						(3, 3, 'Introduction and what you''ll need'),
						(3, 4, 'Checks on who''s in control of your organisation'),
						(4, 1, 'Introduction and what you''ll need'),
						(4, 2, 'Continuity plan for apprenticeship training'),
						(4, 3, 'Equality and diversity policy'),
						(4, 4, 'Safeguarding and Prevent duty policy'),
						(4, 5, 'Health and safety policy'),
						(4, 6, 'Acting as a subcontractor'),
						(5, 1, 'Introduction and what you''ll need'),
						(5, 2, 'Engaging with employers'),
						(5, 3, 'Complaints policy'),
						(5, 4, 'Contract for services template'),
						(5, 5, 'Commitment statement template'),
						(5, 6, 'Prior learning of apprentices'),
						(5, 7, 'English and maths assessments'),
						(5, 8, 'Working with subcontractors'),
						(6, 1, 'Introduction and what you''ll need'),
						(6, 2, 'Type of apprenticeship training'),
						(6, 3, 'Training apprentices'),
						(6, 4, 'Supporting apprentices'),
						(6, 5, 'Forecasting starts'),
						(6, 6, 'Off the job training'),
						(6, 7, 'Where will your apprentices be trained'),
						(7, 1, 'Introduction and what you''ll need'),
						(7, 2, 'Overall accountability for apprenticeships'),
						(7, 3, 'Management hierarchy for apprenticeships'),
						(7, 4, 'Quality and high standards in apprenticeship training'),
						(7, 5, 'Developing and delivering training'),
						(7, 6, 'Sectors and employee experience'),
						(7, 7, 'Policy for professional development of employees'),
						(8, 1, 'Introduction and what you''ll need'),
						(8, 2, 'Process for evaluating the quality of training delivered'),
						(8, 3, 'Process of evaluating the quality of apprenticeship training'),
						(8, 4, 'Systems and processes to collect apprenticeship data'),
						(9, 1, 'Application permissions and checks'),
						(9, 2, 'Quality statement'),
						(9, 3, 'Post application tasks'),
						(9, 4, 'Submit application');


						DELETE FROM [Mtd].[RP_LookupSequenceTitles] 
						/* Inserting into [Mtd].[RP_LookupSequenceTitles] */
						INSERT INTO [Mtd].[RP_LookupSequenceTitles] 
						([SequenceNumber],[Title]) 
						VALUES
						(0, 'Preamble'),
						(1, 'Your organisation'),
						(2, 'Financial evidence'),
						(3, 'Criminal and compliance checks'),
						(4, 'Protecting your apprentices'),
						(5, 'Readiness to engage'),
						(6, 'Planning apprenticeship training'),
						(7, 'Delivering apprenticeship training'),
						(8, 'Evaluating apprenticeship training'),
						(9, 'Finish');


COMMIT TRANSACTION
END

/* Update Log Execution Results as Success if the query ran succesfully*/

UPDATE Mgmt.Log_Execution_Results
   SET Execution_Status=1
      ,EndDateTime=getdate()
	  ,FullJobStatus='Pending'
 WHERE LogId=@LogID
   AND RunID=@RunId

 
END TRY

BEGIN CATCH
    IF @@TRANCOUNT>0
	ROLLBACK TRANSACTION

    DECLARE @ErrorId int

  INSERT INTO Mgmt.Log_Error_Details
	  (UserName
	  ,ErrorNumber
	  ,ErrorState
	  ,ErrorSeverity
	  ,ErrorLine
	  ,ErrorProcedure
	  ,ErrorMessage
	  ,ErrorDateTime
	  ,RunId
	  )
  SELECT 
        SUSER_SNAME(),
	    ERROR_NUMBER(),
	    ERROR_STATE(),
	    ERROR_SEVERITY(),
	    ERROR_LINE(),
	    'LoadROATPLookupData',
	    ERROR_MESSAGE(),
	    GETDATE(),
		@RunId as RunId; 

  SELECT @ErrorId=MAX(ErrorId) FROM Mgmt.Log_Error_Details

/* Update Log Execution Results as Fail if there is an Error*/

UPDATE Mgmt.Log_Execution_Results
   SET Execution_Status=0
      ,EndDateTime=getdate()
	  ,ErrorId=@ErrorId
 WHERE LogId=@LogID
   AND RunID=@RunId

  END CATCH

GO
