CREATE PROCEDURE [dbo].[LoadRPLookupData]
(
   @RunId int
)
AS

-- ==================================================
-- Author:      Sarma Evani
-- Create Date: 29/06/2021
-- Description: Load ROATP Lookup Data
-- ==================================================

BEGIN TRY

    SET NOCOUNT ON

 DECLARE @LogID int

/* Start Logging Execution */

  INSERT INTO Mgmt.Log_Execution_Results
	  (
	    RunId
	   ,StepNo
	   ,StoredProcedureName
	   ,StartDateTime
	   ,Execution_Status
	  )
  SELECT 
        @RunId
	   ,'Step-3'
	   ,'LoadROATPLookupData'
	   ,getdate()
	   ,0

   SELECT @LogID=MAX(LogId) FROM Mgmt.Log_Execution_Results
   WHERE StoredProcedureName='LoadROATPLookupData'
     AND RunId=@RunID


IF @@TRANCOUNT=0
BEGIN
	BEGIN TRANSACTION

	DELETE FROM [Mtd].[RP_LookupOversightReviewStatus]

	/* Isert into [Mtd].[RP_LookupOversightReviewStatus] */
	INSERT INTO [Mtd].[RP_LookupOversightReviewStatus] 
	([Status],[Description]) 
	VALUES 
	(1, 'Successful'),
	(2, 'Successful - Already Active'),
	(3, 'Successful - Fitness For Funding'),
	(4, 'Unsuccessful'),
	(5, 'In Progress'),
	(6, 'Rejected'),
	(7, 'Withdrawn'),
	(8, 'Removed');



	DELETE FROM [Mtd].[RP_LookupPageTitles]
	/* insert into [Mtd].[RP_LookupPageTitles]*/
	INSERT INTO [Mtd].[RP_LookupPageTitles]
	([SequenceNumber],[SectionNumber],[PageId],[Title])	
	VALUES
			(0, 1, '1', 'Preamble'),
			(0, 1, '2', 'Provider route'),
			(0, 1, '3', 'Conditions of acceptance'),

			(1, 1, '10', 'Your organisation'),
			(1, 1, '11', 'Your organisation'),
			(1, 1, '12', 'Your organisation'),

			(1, 2, '20', 'Does your organisation have an ultimate parent company in the UK?'),
			(1, 2, '21', 'Enter your organisation''s ultimate parent company details'),
			(1, 2, '30', 'What is your organisation''s Information Commissioner''s Office (ICO) registration number?'),
			(1, 2, '40', 'Does your organisation have a website?'),

			(1, 3, '70', 'Confirm who''s in control - Companies House'),
			(1, 3, '80', 'Confirm who''s in control - Trustees'),
			(1, 3, '90', 'Confirm who''s in control - Add Trustees'),
			(1, 3, '100', 'Tell us your organisation''s type'),
			(1, 3, '101', 'What is your organisation''s partner?'),
			(1, 3, '110', 'Enter the individual''s details'),
			(1, 3, '111', 'Enter the organisation''s details'),
			(1, 3, '120', 'What is individual''s date of birth?'),
			(1, 3, '130', 'Confirm who''s in control - Manual Entry'),

			(1, 4, '140', 'What is your organisation?'),
			(1, 4, '150', 'What is your organisation?'),
			(1, 4, '160', 'What type of educational institute is your organisation?'),
			(1, 4, '170', 'What type of public body is your organisation?'),
			(1, 4, '180', 'What type of school is your organisation?'),
			(1, 4, '200', 'Is your organisation registered and receiving funding from ESFA?'),
			(1, 4, '210', 'Is your organisation receiving funding from ESFA?'),
			(1, 4, '220', 'Is your organisation monitored and supported by the Office of Students?'),
			(1, 4, '230', 'How would you describe your organisation?'),
			(1, 4, '50', 'How long has your organisation been actively trading?'),
			(1, 4, '60', 'How long has your organisation been actively trading?'),
			(1, 4, '10001', 'Your organisation is not eligible to apply to join RoATP'),
			(1, 4, '10002', 'Your organisation is not eligible to apply to join RoATP'),
			(1, 4, '10003', 'Your organisation is not eligible to apply to join RoATP'),

			(1, 5, '235', 'Is your organisation funded by the Office for Students?'),
			(1, 5, '240', 'Does your organisation offer initial teacher training?'),
			(1, 5, '250', 'Is the postgraduate teaching apprenticeship the only apprenticeship your organisation intends to deliver?'),
			(1, 5, '260', 'Has your organisation had a full Ofsted inspection in further education and skills?'),
			(1, 5, '270', 'Did your organisation get a grade for apprenticeships in this full Ofsted inspection?'),
			(1, 5, '280', 'What grade did your organisation get for overall effectiveness in this full Ofsted inspection?'),
			(1, 5, '290', 'Has your organisation had a monitoring visit for apprenticeships in further education and skills?'),
			(1, 5, '292', 'Has your organisation had 2 consecutive monitoring visits with the grade ''insufficient progress''?'),
			(1, 5, '294', 'Was the most recent monitoring visit within the last 18 months?'),
			(1, 5, '300', 'What grade did your organisation get for apprenticeships in this full Ofsted inspection?'),
			(1, 5, '301', 'What grade did your organisation get for apprenticeships in this full Ofsted inspection?'),
			(1, 5, '310', 'Did your organisation get this grade within the last 3 years?'),
			(1, 5, '311', 'Did your organisation get this grade within the last 3 years?'),
			(1, 5, '320', 'Has your organisation maintained funding from an education agency since its full Ofsted inspection?'),
			(1, 5, '330', 'Has your organisation had a short Ofsted inspection within the last 3 years?'),
			(1, 5, '340', 'Has your organisation maintained the grade it got in its full Ofsted inspection in its short Ofsted inspection?'),
			(1, 5, '350', 'Has your organisation delivered apprenticeship training as a subcontractor in the last 12 months?'),
			(1, 5, '360', 'Upload a copy of a legally binding contract between your organisation and a main or employer provider'),
			(1, 5, '10004', 'Your organisation is not eligible to apply to join RoATP'),
			(1, 5, '10010', 'Your organisation is not eligible to apply to join RoATP'),

			(2, 1, '2000', 'Financial health assessment'),
			(2, 1, '2010', 'Financial health assessment'),

			(2, 2, '2100', 'Was your organisation''s total annual turnover over £75 million for the latest reported financial year?'),
			(2, 2, '2110', 'Does your organisation expect its funding from ESFA to be less than 5% of its total annual turnover?'),
			(2, 2, '2120', 'Financial evidence'),
			(2, 2, '2130', 'Financial evidence'),
			(2, 2, '2140', 'Financial evidence'),
			(2, 2, '2150', 'Has your organisation produced its latest full financial statements covering a minimum of 12 months?'),
			(2, 2, '2160', 'Upload your organisation''s latest full financial statements covering the last 12 months'),
			(2, 2, '2170', 'Has your organisation produced financial statements covering any period within the last 12 months?'),
			(2, 2, '2180', 'What you need to upload'),
			(2, 2, '2190', 'Upload your organisation''s financial statements covering any period within the last 12 months'),
			(2, 2, '2195', 'What you need to upload'),
			(2, 2, '2200', 'Upload your organisation''s management accounts covering the remaining period to date'),
			(2, 2, '2210', 'Has your organisation produced full management accounts covering the last 12 months?'),
			(2, 2, '2220', 'What you need to upload'),
			(2, 2, '2225', 'Upload your organisation''s full management accounts for the last 12 months'),
			(2, 2, '2230', 'What you need to upload'),
			(2, 2, '2240', 'Upload your organisation''s management accounts covering at least 3 months within the last 12 months'),
			(2, 2, '2250', 'Upload your organisation''s financial projections covering the remaining period'),
			(2, 2, '2260', 'Who prepared the answers and uploads in this section?'),
			(2, 2, '2270', 'What''s the accounting reference date for the financial information you are submitting?'),
			(2, 2, '2280', 'How many months does the accounting period cover for the financial information you are submitting?'),

			(2, 3, '2500', 'Does your UK ultimate parent company have consolidated financial statements?'),
			(2, 3, '2510', 'Upload your UK ultimate parent company''s consolidated financial statements'),
			(2, 3, '2520', 'Does your UK ultimate parent company have other active subsidiary companies?'),
			(2, 3, '2530', 'Upload a financial statement for all your UK ultimate parent company''s active subsidiary companies'),
			(2, 3, '2540', 'Upload your UK ultimate parent company''s full financial statements covering the last 12 months'),

			(3, 1, '3000', 'Criminal and compliance checks on your organisation'),

			(3, 2, '3100', 'Does your organisation have any composition with creditors?'),
			(3, 2, '3110', 'Has your organisation failed to pay back funds in the last 3 years?'),
			(3, 2, '3120', 'Has your organisation had a contract terminated early by a public body in the last 3 years?'),
			(3, 2, '3130', 'Has your organisation withdrawn from a contract with a public body in the last 3 years?'),
			(3, 2, '3135', 'Has your organisation been removed from the Register of Training Organisations (RoTO) in the last 3 years?'),
			(3, 2, '3140', 'Has your organisation had funding removed from any education bodies in the last 3 years?'),
			(3, 2, '3150', 'Has your organisation been removed from any professional or trade registers in the last 3 years?'),
			(3, 2, '3160', 'Has your organisation been involuntarily withdrawn from Initial Teacher Training accreditation in the last 3 years?'),
			(3, 2, '3170', 'Has your organisation been removed from any charity register?'),
			(3, 2, '3180', 'Has your organisation been investigated due to safeguarding issues in the last 3 months?'),
			(3, 2, '3190', 'Is your organisation currently, or has within the last 5 years been, subject to an investigation by the ESFA or other public body or regulator?'),
			(3, 2, '3199', 'Has your organisation been subject to insolvency or winding up proceedings in the last 3 years?'),

			(3, 3, '3200', 'Criminal and compliance checks on who''s in control of your organisation'),

			(3, 4, '3300', 'Does anyone who''s in control of your organisation have any unspent criminal convictions?'),
			(3, 4, '3301', 'Do you have any unspent criminal convictions?'),
			(3, 4, '3310', 'Has anyone who''s in control of your organisation failed to pay back funds in the last 3 years?'),
			(3, 4, '3311', 'Have you failed to pay back funds in the last 3 years?'),
			(3, 4, '3320', 'Has anyone who''s in control of your organisation been investigated for fraud or irregularities in the last 3 years?'),
			(3, 4, '3321', 'Have you been investigated for fraud or irregularities in the last 3 years?'),
			(3, 4, '3330', 'Does anyone who''s in control of your organisation have any ongoing investigations for fraud or irregularities?'),
			(3, 4, '3331', 'Do you have any ongoing investigations for fraud or irregularities?'),
			(3, 4, '3340', 'Has anyone who''s in control of your organisation had a contract terminated by a public body in the last 3 years?'),
			(3, 4, '3341', 'Have you had a contract terminated by a public body in the last 3 years?'),
			(3, 4, '3350', 'Has anyone who''s in control of your organisation withdrawn from a contract with a public body in the last 3 years?'),
			(3, 4, '3351', 'Have you withdrawn from a contract with a public body in the last 3 years?'),
			(3, 4, '3360', 'Has anyone who''s in control of your organisation breached tax payments or social security contributions in the last 3 years?'),
			(3, 4, '3361', 'Have you breached tax payments or social security contributions in the last 3 years?'),
			(3, 4, '3370', 'Is anyone who''s in control of your organisation on the Register of Removed Trustees?'),
			(3, 4, '3371', 'Are you on the Register of Removed Trustees?'),
			(3, 4, '3380', 'Has anyone who''s in control of your organisation or any of its partner organisations been made bankrupt in the last 3 years?'),
			(3, 4, '3381', 'Have you been made bankrupt in the last 3 years?'),
			(3, 4, '3390', 'Has anyone who''s in control of your organisation, or any of its partner organisations, been subject to a prohibition order from the Teaching Regulation Agency on behalf of the Secretary of State for Education?'),
			(3, 4, '3391', 'Have you been subject to a prohibition order from the Teaching Regulation Agency on behalf of the Secretary of State for Education?'),
			(3, 4, '3395', 'Has anyone who''s in control of your organisation, or any of its partner organisations, been subject to a ban from management or governance of schools?'),
			(3, 4, '3396', 'Have you been subject to a ban from  management or governance of schools?'),

			(4, 1, '4000', 'Protecting your apprentices'),
			(4, 1, '4001', 'Protecting your apprentices'),
			(4, 1, '4002', 'Protecting your apprentices'),

			(4, 2, '4010', 'Upload your organisation''s continuity plan for apprenticeship training'),

			(4, 3, '4020', 'Upload your organisation''s equality and diversity policy'),

			(4, 4, '4030', 'Upload your organisation''s safeguarding policy'),
			(4, 4, '4035', 'Tell us who has overall responsibility for safeguarding in your organisation'),
			(4, 4, '4037', 'Does your organisation''s safeguarding policy include its responsibilities towards the Prevent duty?'),
			(4, 4, '4038', 'Upload your organisation''s Prevent duty policy'),

			(4, 5, '4040', 'Upload your organisation''s health and safety policy'),
			(4, 5, '4045', 'Tell us who has overall responsibility for health and safety in your organisation'),

			(4, 6, '4050', 'When acting as a subcontractor, will your organisation follow its lead provider''s policies and plans?'),

			(5, 1, '5000', 'Readiness to engage'),
			(5, 1, '5010', 'Readiness to engage'),
			(5, 1, '5020', 'Readiness to engage'),

			(5, 2, '5100', 'Has your organisation engaged with employers to deliver apprenticeship training to their employees?'),
			(5, 2, '5110', 'How will your organisation manage its relationship with employers?'),
			(5, 2, '5120', 'Tell us who''s responsible for managing relationships with employers'),
			(5, 2, '5130', 'How will your organisation promote apprenticeships to employers?'),

			(5, 3, '5200', 'Upload your organisation''s complaints policy'),
			(5, 3, '5210', 'Enter the website link for your organisation''s complaints policy'),

			(5, 4, '5300', 'Upload your organisation''s contract for services template with employers'),

			(5, 5, '5400', 'Upload your organisation''s commitment statement template'),

			(5, 6, '5500', 'What is your organisation''s process for initial assessments to recognise prior learning?'),
			(5, 6, '5510', 'What is your organisation''s process to assess English and maths qualifications for apprentices?'),

			(5, 7, '5550', 'How will you deliver the assessments in English and maths?'),
			(5, 7, '5560', 'Where will you deliver the assessments in English and maths?'),
			(5, 7, '5570', 'How will you continue to deliver English and maths training and assessments if there''s a significant event?'),

			(5, 8, '5600', 'Does your organisation expect to use subcontractors in the first 12 months of joining RoATP?'),
			(5, 8, '5610', 'How will your organisation carry out due diligence on its subcontractors?'),

			(6, 1, '6000', 'Planning apprenticeship training'),
			(6, 1, '6001', 'Planning apprenticeship training'),
			(6, 1, '6002', 'Planning apprenticeship training'),

			(6, 2, '6201', 'What type of apprenticeship training will your organisation offer?'),
			(6, 2, '6202', 'What type of apprenticeship training will your organisation offer?'),
			(6, 2, '6203', 'What type of apprenticeship training will your organisation offer?'),
			(6, 2, '6230', 'Tell us how your organisation is ready to deliver training in apprenticeship standards'),
			(6, 2, '6250', 'Does your organisation have a plan to transition from apprenticeship frameworks to apprenticeship standards?'),
			(6, 2, '6252', 'How will your organisation transition from apprenticeship frameworks to apprenticeship standards?'),
			(6, 2, '6253', 'How will your organisation transition from apprenticeship frameworks to apprenticeship standards?'),
			(6, 2, '6254', 'Why will your organisation only deliver apprenticeship frameworks?'),
			(6, 2, '6260', 'Does your organisation have a plan to transition from apprenticeship frameworks to apprenticeship standards?'),
			(6, 2, '6262', 'How will your organisation transition from apprenticeship frameworks to apprenticeship standards?'),
			(6, 2, '6264', 'Why will your organisation only deliver apprenticeship frameworks?'),
			(6, 2, '6270', 'How will your organisation engage with end-point assessment organisations (EPAOs)?'),
			(6, 2, '6280', 'How will your organisation plan to engage and work with awarding bodies?'),

			(6, 3, '6300', 'How will your organisation train its apprentices?'),

			(6, 4, '6400', 'How will your organisation ensure apprentices are supported during their apprenticeship training?'),
			(6, 4, '6405', 'How will your organisation ensure apprentices are supported during their apprenticeship training?'),
			(6, 4, '6410', 'How will your organisation support its apprentices?'),
			(6, 4, '6420', 'What other ways will your organisation use to support its apprentices?'),

			(6, 5, '6500', 'How many starts does your organisation forecast in the first 12 months of joining the RoATP?'),
			(6, 5, '6510', 'When will your organisation be ready to deliver training against this forecast?'),
			(6, 5, '6520', 'Will your organisation recruit new staff to deliver training against these forecasts?'),
			(6, 5, '6530', 'What is the typical ratio of the staff who deliver training to the apprentices?'),
			(6, 5, '6540', 'How does your proposed staff to learner ratio offer quality support to your apprentices?'),

			(6, 6, '6600', 'What teaching methods will your organisation use to deliver 20% off the job training?'),
			(6, 6, '6610', 'How will your organisation ensure 20% off the job training is relevant to the specific apprenticeship being delivered?'),

			(6, 7, '6700', 'Where will your apprentices be trained?'),

			(7, 1, '7000', 'Delivering apprenticeship training'),
			(7, 1, '7001', 'Delivering apprenticeship training'),
			(7, 1, '7002', 'Delivering apprenticeship training'),

			(7, 2, '7100', 'Tell us who has overall accountability for apprenticeships in your organisation'),

			(7, 3, '7200', 'Confirm management hierarchy'),

			(7, 4, '7300', 'Upload your management hierarchy''s expectations for quality and high standards in apprenticeship training'),
			(7, 4, '7305', 'Tell us how these expectations for quality and high standards in apprenticeship training are monitored and evaluated'),
			(7, 4, '7310', 'Tell us who''s responsible for maintaining these expectations for quality and high standards in apprenticeship training'),
			(7, 4, '7320', 'How are these expectations for quality and high standards in apprenticeship training communicated to employees'),

			(7, 5, '7500', 'Does your organisation have a team responsible for developing and delivering training?'),
			(7, 5, '7510', 'Does your organisation have someone responsible for developing and delivering training?'),
			(7, 5, '7520', 'Does your organisation have someone responsible for developing and delivering training?'),
			(7, 5, '7530', 'Who has the team worked with to develop and deliver training?'),
			(7, 5, '7540', 'Tell us who''s the overall manager for this team'),
			(7, 5, '7560', 'Who has this person worked with to develop and deliver training?'),
			(7, 5, '7570', 'How has the team worked with other organisations to develop and deliver training?'),
			(7, 5, '7590', 'Tell us who''s the overall manager for this team'),
			(7, 5, '7591', 'How has the team worked with other organisations and employers to develop and deliver training?'),
			(7, 5, '7592', 'How has the team worked with employers to develop and deliver training?'),
			(7, 5, '7593', 'How has this person worked with other organisations to develop and deliver training?'),
			(7, 5, '7594', 'How has this person worked with other organisations and employers to develop and deliver training?'),
			(7, 5, '7595', 'How has this person worked with employers to develop and deliver training?'),

			(7, 6, '7600', 'What sectors will your organisation deliver apprenticeship training in?'),
			(7, 6, '7610AA', 'What standards do you intend to deliver within the ''Agriculture, environmental and animal care'' sector?'),
			(7, 6, '7610A', 'How many starts does your organisation forecast in the ''Agriculture, environmental and animal care'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7610B', 'How many employees will deliver training in the ''Agriculture, environmental and animal care'' sector?'),
			(7, 6, '7610', 'Who''s the most experienced employee in the ''Agriculture, environmental and animal care'' sector?'),
			(7, 6, '7611', 'Most Experienced Employee''s experience in the ''Agriculture, environmental and animal care'' sector'),
			(7, 6, '7612', 'Most Experienced Employee''s experience in the ''Agriculture, environmental and animal care'' sector'),
			(7, 6, '7613', 'Most Experienced Employee''s experience in the ''Agriculture, environmental and animal care'' sector'),
			(7, 6, '7615AA', 'What standards do you intend to deliver within the ''Business and administration'' sector?'),
			(7, 6, '7615A', 'How many starts does your organisation forecast in the ''Business and administration'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7615B', 'How many employees will deliver training in the ''Business and administration'' sector?'),
			(7, 6, '7615', 'Who''s the most experienced employee in the ''Business and administration'' sector?'),
			(7, 6, '7616', 'Most Experienced Employee''s experience in the ''Business and administration'' sector'),
			(7, 6, '7617', 'Most Experienced Employee''s experience in the ''Business and administration'' sector'),
			(7, 6, '7618', 'Most Experienced Employee''s experience in the ''Business and administration'' sector'),
			(7, 6, '7620AA', 'What standards do you intend to deliver within the ''Care services'' sector?'),
			(7, 6, '7620A', 'How many starts does your organisation forecast in the ''Care services'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7620B', 'How many employees will deliver training in the ''Care services'' sector?'),
			(7, 6, '7620', 'Who''s the most experienced employee in the ''Care services'' sector?'),
			(7, 6, '7621', 'Most Experienced Employee''s experience in the ''Care services'' sector'),
			(7, 6, '7622', 'Most Experienced Employee''s experience in the ''Care services'' sector'),
			(7, 6, '7623', 'Most Experienced Employee''s experience in the ''Care services'' sector'),
			(7, 6, '7625AA', 'What standards do you intend to deliver within the ''Catering and hospitality'' sector?'),
			(7, 6, '7625A', 'How many starts does your organisation forecast in the ''Catering and hospitality'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7625B', 'How many employees will deliver training in the ''Catering and hospitality'' sector?'),
			(7, 6, '7625', 'Who''s the most experienced employee in the ''Catering and hospitality'' sector?'),
			(7, 6, '7626', 'Most Experienced Employee''s experience in the ''Catering and hospitality'' sector'),
			(7, 6, '7627', 'Most Experienced Employee''s experience in the ''Catering and hospitality'' sector'),
			(7, 6, '7628', 'Most Experienced Employee''s experience in the ''Catering and hospitality'' sector'),
			(7, 6, '7630AA', 'What standards do you intend to deliver within the ''Construction'' sector?'),
			(7, 6, '7630A', 'How many starts does your organisation forecast in the ''Construction'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7630B', 'How many employees will deliver training in the ''Construction'' sector?'),
			(7, 6, '7630', 'Who''s the most experienced employee in the ''Construction'' sector?'),
			(7, 6, '7631', 'Most Experienced Employee''s experience in the ''Construction'' sector'),
			(7, 6, '7632', 'Most Experienced Employee''s experience in the ''Construction'' sector'),
			(7, 6, '7633', 'Most Experienced Employee''s experience in the ''Construction'' sector'),
			(7, 6, '7635AA', 'What standards do you intend to deliver within the ''Creative and design'' sector?'),
			(7, 6, '7635A', 'How many starts does your organisation forecast in the ''Creative and design'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7635B', 'How many employees will deliver training in the ''Creative and design'' sector?'),
			(7, 6, '7635', 'Who''s the most experienced employee in the ''Creative and design'' sector?'),
			(7, 6, '7636', 'Most Experienced Employee''s experience in the ''Creative and design'' sector'),
			(7, 6, '7637', 'Most Experienced Employee''s experience in the ''Creative and design'' sector'),
			(7, 6, '7638', 'Most Experienced Employee''s experience in the ''Creative and design'' sector'),
			(7, 6, '7640AA', 'What standards do you intend to deliver within the ''Digital'' sector?'),
			(7, 6, '7640A', 'How many starts does your organisation forecast in the ''Digital'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7640B', 'How many employees will deliver training in the ''Digital'' sector?'),
			(7, 6, '7640', 'Who''s the most experienced employee in the ''Digital'' sector?'),
			(7, 6, '7641', 'Most Experienced Employee''s experience in the ''Digital'' sector'),
			(7, 6, '7642', 'Most Experienced Employee''s experience in the ''Digital'' sector'),
			(7, 6, '7643', 'Most Experienced Employee''s experience in the ''Digital'' sector'),
			(7, 6, '7645AA', 'What standards do you intend to deliver within the ''Education and childcare'' sector?'),
			(7, 6, '7645A', 'How many starts does your organisation forecast in the ''Education and childcare'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7645B', 'How many employees will deliver training in the ''Education and childcare'' sector?'),
			(7, 6, '7645', 'Who''s the most experienced employee in the ''Education and childcare'' sector?'),
			(7, 6, '7646', 'Most Experienced Employee''s experience in the ''Education and childcare'' sector'),
			(7, 6, '7647', 'Most Experienced Employee''s experience in the ''Education and childcare'' sector'),
			(7, 6, '7648', 'Most Experienced Employee''s experience in the ''Education and childcare'' sector'),
			(7, 6, '7650AA', 'What standards do you intend to deliver within the ''Engineering and manufacturing'' sector?'),
			(7, 6, '7650A', 'How many starts does your organisation forecast in the ''Engineering and manufacturing'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7650B', 'How many employees will deliver training in the ''Engineering and manufacturing'' sector?'),
			(7, 6, '7650', 'Who''s the most experienced employee in the ''Engineering and manufacturing'' sector?'),
			(7, 6, '7651', 'Most Experienced Employee''s experience in the ''Engineering and manufacturing'' sector'),
			(7, 6, '7652', 'Most Experienced Employee''s experience in the ''Engineering and manufacturing'' sector'),
			(7, 6, '7653', 'Most Experienced Employee''s experience in the ''Engineering and manufacturing'' sector'),
			(7, 6, '7655AA', 'What standards do you intend to deliver within the ''Hair and Beauty'' sector?'),
			(7, 6, '7655A', 'How many starts does your organisation forecast in the ''Hair and Beauty'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7655', 'How many employees will deliver training in the ''Hair and Beauty'' sector?'),
			(7, 6, '7655B', 'Who''s the most experienced employee in the ''Hair and Beauty'' sector?'),
			(7, 6, '7656', 'Most Experienced Employee''s experience in the ''Hair and Beauty'' sector'),
			(7, 6, '7657', 'Most Experienced Employee''s experience in the ''Hair and Beauty'' sector'),
			(7, 6, '7658', 'Most Experienced Employee''s experience in the ''Hair and Beauty'' sector'),
			(7, 6, '7660AA', 'What standards do you intend to deliver within the ''Health and science'' sector?'),
			(7, 6, '7660A', 'How many starts does your organisation forecast in the ''Health and science'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7660B', 'How many employees will deliver training in the ''Health and science'' sector?'),
			(7, 6, '7660', 'Who''s the most experienced employee in the ''Health and science'' sector?'),
			(7, 6, '7661', 'Most Experienced Employee''s experience in the ''Health and science'' sector'),
			(7, 6, '7662', 'Most Experienced Employee''s experience in the ''Health and science'' sector'),
			(7, 6, '7663', 'Most Experienced Employee''s experience in the ''Health and science'' sector'),
			(7, 6, '7665AA', 'What standards do you intend to deliver within the ''Legal, finance and accounting'' sector?'),
			(7, 6, '7665A', 'How many starts does your organisation forecast in the ''Legal, finance and accounting'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7665B', 'How many employees will deliver training in the ''Legal, finance and accounting'' sector?'),
			(7, 6, '7665', 'Who''s the most experienced employee in the ''Legal, finance and accounting'' sector?'),
			(7, 6, '7666', 'Most Experienced Employee''s experience in the ''Legal, finance and accounting'' sector'),
			(7, 6, '7667', 'Most Experienced Employee''s experience in the ''Legal, finance and accounting'' sector'),
			(7, 6, '7668', 'Most Experienced Employee''s experience in the ''Legal, finance and accounting'' sector'),
			(7, 6, '7670AA', 'What standards do you intend to deliver within the ''Protective services'' sector?'),
			(7, 6, '7670A', 'How many starts does your organisation forecast in the ''Protective services'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7670B', 'How many employees will deliver training in the ''Protective services'' sector?'),
			(7, 6, '7670', 'Who''s the most experienced employee in the ''Protective services'' sector?'),
			(7, 6, '7671', 'Most Experienced Employee''s experience in the ''Protective services'' sector'),
			(7, 6, '7672', 'Most Experienced Employee''s experience in the ''Protective services'' sector'),
			(7, 6, '7673', 'Most Experienced Employee''s experience in the ''Protective services'' sector'),
			(7, 6, '7675AA', 'What standards do you intend to deliver within the ''Sales, marketing and procurement'' sector?'),
			(7, 6, '7675A', 'How many starts does your organisation forecast in the ''Sales, marketing and procurement'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7675B', 'How many employees will deliver training in the ''Sales, marketing and procurement'' sector?'),
			(7, 6, '7675', 'Who''s the most experienced employee in the ''Sales, marketing and procurement'' sector?'),
			(7, 6, '7676', 'Most Experienced Employee''s experience in the ''Sales, marketing and procurement'' sector'),
			(7, 6, '7677', 'Most Experienced Employee''s experience in the ''Sales, marketing and procurement'' sector'),
			(7, 6, '7678', 'Most Experienced Employee''s experience in the ''Sales, marketing and procurement'' sector'),
			(7, 6, '7680AA', 'What standards do you intend to deliver within the ''Transport and logistics'' sector?'),
			(7, 6, '7680A', 'How many starts does your organisation forecast in the ''Transport and logistics'' sector in the first 12 months of joining the RoATP?'),
			(7, 6, '7680B', 'How many employees will deliver training in the ''Transport and logistics'' sector?'),
			(7, 6, '7680', 'Who''s the most experienced employee in the ''Transport and logistics'' sector?'),
			(7, 6, '7681', 'Most Experienced Employee''s experience in the ''Transport and logistics'' sector'),
			(7, 6, '7682', 'Most Experienced Employee''s experience in the ''Transport and logistics'' sector'),
			(7, 6, '7683', 'Most Experienced Employee''s experience in the ''Transport and logistics'' sector'),

			(7, 7, '7700', 'Upload your organisation''s contract for services template with employers'),
			(7, 7, '7710', 'Give an example of how your organisation used this policy to improve employee sector expertise'),
			(7, 7, '7720', 'Give an example of how your organisation used this policy to maintain employee teaching and training knowledge'),

			(8, 1, '8000', 'Evaluating apprenticeship training'),
			(8, 1, '8010', 'Evaluating apprenticeship training'),

			(8, 2, '8100', 'What is your organisation''s process for evaluating the quality of training delivered?'),
			(8, 2, '8110', 'How has your organisation made improvements using its process for evaluating the quality of training delivered?'),

			(8, 3, '8200', 'Does your organisation''s process for evaluating the quality of training delivered include apprenticeship training?'),
			(8, 3, '8210', 'How will your organisation evaluate the quality of apprenticeship training?'),
			(8, 3, '8220', 'How will your organisation evaluate the quality of apprenticeship training?'),
			(8, 3, '8230', 'How will your organisation review its process for evaluating the quality of training delivered?'),

			(8, 4, '8300', 'Does your organisation have systems and processes in place to collect apprenticeship data?'),
			(8, 4, '8310', 'Does your organisation have the resources to submit Individualised Learner Record (ILR) data?'),
			(8, 4, '8320', 'Who is the individual accountable for submitting ILR data for your organisation?'),

			(9, 1, '9000', 'Do you have permission from everyone named in this application to use their details?'),
			(9, 1, '9010', 'Have you checked with everyone named in this application that the details provided for them are accurate?'),
			(9, 1, '9020', 'Do you have permission from your organisation to submit this application?'),
			(9, 1, '10005', 'Before you submit your application'),

			(9, 2, '9100', 'Do you understand that your organisation must develop and deliver apprenticeship training in line with the Institute for Apprenticeships and Technical Education''s ''quality statement''?'),
			(9, 2, '100055', 'Before you submit your application'),

			(9, 3, '9200', 'Do you understand that your organisation will not join the RoATP until it completes all post application tasks?'),
			(9, 3, '10006', 'Before you submit your application');


			DELETE FROM [Mtd].[RP_LookupQuestionTitles]
			/* Insert into [Mtd].[RP_LookupQuestionTitles]*/
			INSERT INTO [Mtd].[RP_LookupQuestionTitles]
			([SequenceNumber],[SectionNumber],[PageId],[QuestionId],[Title])
				VALUES 				
					(0, 1, '1', 'PRE-10', 'UKPRN'),
					(0, 1, '1', 'PRE-20', 'UKRLP Legal Name'),
					(0, 1, '1', 'PRE-30', 'UKRLP Website'),
					(0, 1, '1', 'PRE-31', 'No UKRLP Website'),
					(0, 1, '1', 'PRE-40', 'UKRLP Legal Address Line1'),
					(0, 1, '1', 'PRE-41', 'UKRLP Legal Address Line2'),
					(0, 1, '1', 'PRE-42', 'UKRLP Legal Address Line3'),
					(0, 1, '1', 'PRE-43', 'UKRLP Legal Address Line4'),
					(0, 1, '1', 'PRE-44', 'UKRLP Legal Address Town'),
					(0, 1, '1', 'PRE-45', 'UKRLP Legal Address Postcode'),
					(0, 1, '1', 'PRE-46', 'UKRLP Trading Name'),
					(0, 1, '1', 'PRE-50', 'Companies House Manual Entry Required'),
					(0, 1, '1', 'PRE-51', 'UKRLP Verification Company Number'),
					(0, 1, '1', 'PRE-52', 'Companies House Company Name'),
					(0, 1, '1', 'PRE-53', 'Companies House Company Type'),
					(0, 1, '1', 'PRE-54', 'Companies House Company Status'),
					(0, 1, '1', 'PRE-55', 'Companies House Incorporation Date'),
					(0, 1, '1', 'PRE-56', 'UKRLP Verification Company'),
					(0, 1, '1', 'PRE-60', 'Charity Commission Trustee Manual Entry'),
					(0, 1, '1', 'PRE-61', 'UKRLP Verification Charity Registration Number'),
					(0, 1, '1', 'PRE-62', 'Charity Commission Charity Name'),
					(0, 1, '1', 'PRE-64', 'Charity Commission Registration Date'),
					(0, 1, '1', 'PRE-65', 'UKRLP Verification Charity'),
					(0, 1, '1', 'PRE-70', 'UKRLP Verification Soletrader or Partnership'),
					(0, 1, '1', 'PRE-80', 'UKRLP Primary Verification Source'),
					(0, 1, '1', 'PRE-90', 'On RoATP'),
					(0, 1, '1', 'PRE-91', 'RoATP Current Status'),
					(0, 1, '1', 'PRE-92', 'RoATP Removed Reason'),
					(0, 1, '1', 'PRE-93', 'RoATP Status Date'),
					(0, 1, '1', 'PRE-94', 'RoATP Provider Route'),
					(0, 1, '1', 'PRE-95', 'Levy Paying Employer'),
					(0, 1, '2', 'YO-1', 'Apply Provider Route'),
					(0, 1, '3', 'COA-1', 'Conditions of Acceptance accepted'),
					(1, 2, '20', 'YO-20', 'Has Parent Company'),
					(1, 2, '21', 'YO-21', 'Company number'),
					(1, 2, '21', 'YO-22', 'Company name'),
					(1, 2, '30', 'YO-30', 'ICO registration number'),
					(1, 2, '40', 'YO-40', 'Has Website'),
					(1, 2, '40', 'YO-41', 'Website address'),
					(1, 3, '100', 'YO-100', 'Soletrader Or Partnership'),
					(1, 3, '101', 'YO-101', 'Partnership Type'),
					(1, 3, '110', 'YO-110', 'Individual''s details'),
					(1, 3, '111', 'YO-111', 'Organisation''s details'),
					(1, 3, '120', 'YO-120', 'Date of birth'),
					(1, 3, '130', 'YO-130', 'Add People In Control'),
					(1, 3, '70', 'YO-70', 'Companies House Directors'),
					(1, 3, '70', 'YO-71', 'Companies House PSCs'),
					(1, 3, '70', 'YO-75', 'Directors and PSCs Confirmed'),
					(1, 3, '80', 'YO-80', 'Charity Trustees'),
					(1, 3, '80', 'YO-85', 'Confirm Trustees'),
					(1, 3, '90', 'YO-90', 'Add Trustees'),
					(1, 4, '10001', 'SHUT-001', 'Shutter Page - Actively trading for at least 12 months'),
					(1, 4, '10002', 'SHUT-002', 'Shutter Page - Actively trading for at least 12 months'),
					(1, 4, '10003', 'SHUT-003', 'Shutter Page - Actively trading for at least 3 months'),
					(1, 4, '140', 'YO-140', 'Organisation Type'),
					(1, 4, '150', 'YO-150', 'Organisation Type'),
					(1, 4, '160', 'YO-160', 'Education Institute Type'),
					(1, 4, '170', 'YO-170', 'Public Body Type'),
					(1, 4, '180', 'YO-180', 'School Type'),
					(1, 4, '200', 'YO-200', 'Registered with ESFA'),
					(1, 4, '210', 'YO-210', 'Funded by ESFA'),
					(1, 4, '220', 'YO-220', 'Monitored by Office of Students'),
					(1, 4, '230', 'YO-230', 'Organisation Description'),
					(1, 4, '50', 'YO-50', 'Actively Trading'),
					(1, 4, '60', 'YO-60', 'Actively Trading'),
					(1, 5, '235', 'YO-235', 'Funded by Office of Students'),
					(1, 5, '240', 'YO-240', 'ITT Accredited'),
					(1, 5, '250', 'YO-250', 'Postgraduate Teaching Apprenticeship Only'),
					(1, 5, '260', 'YO-260', 'Full Ofsted Inspection'),
					(1, 5, '270', 'YO-270', 'Full Ofsted Graded'),
					(1, 5, '280', 'YO-280', 'Full Ofsted Grade'),
					(1, 5, '290', 'YO-290', 'Has Had Monitoring Visit'),
					(1, 5, '292', 'YO-292', 'Has 2 Monitoring Visits Graded Inadequate'),
					(1, 5, '294', 'YO-294', 'Has Monitoring Visit Graded Inadequate in Last 18 Months'),
					(1, 5, '300', 'YO-300', 'Ofsted Apprenticeships Grade'),
					(1, 5, '301', 'YO-301', 'Ofsted Apprenticeships Grade'),
					(1, 5, '310', 'YO-310', 'Ofsted Grade in Last 3 Years'),
					(1, 5, '311', 'YO-311', 'Ofsted Grade in Last 3 Years'),
					(1, 5, '320', 'YO-320', 'Maintained Funding'),
					(1, 5, '330', 'YO-330', 'Had Short Inspection'),
					(1, 5, '340', 'YO-340', 'Maintained Short Inspection Grade'),
					(1, 5, '350', 'YO-350', 'Has Delivered Training as Subcontractor'),
					(1, 5, '360', 'YO-360', 'File'),
					(2, 2, '2100', 'FH-30', 'Over £75 million for the latest reported financial year'),
					(2, 2, '2110', 'FH-40', 'ESFA funding to be less than 5% annual turnover'),
					(2, 2, '2120', 'FH-100', 'Enter your organisation''s total current liabilities for the latest reported financial year'),
					(2, 2, '2120', 'FH-110', 'Enter your organisation''s total borrowings for the latest reported financial year'),
					(2, 2, '2120', 'FH-120', 'Enter your organisation''s net assets for the latest reported financial year'),
					(2, 2, '2120', 'FH-130', 'Enter your organisation''s total intangible assets for the latest reported financial year'),
					(2, 2, '2120', 'FH-50', 'Enter your organisation''s total annual turnover for the latest reported financial year'),
					(2, 2, '2120', 'FH-550', 'Enter your organisation''s average number of Full Time Equivalent (FTE) employees for the last financial year'),
					(2, 2, '2120', 'FH-60', 'Enter your organisation''s total depreciation and amortisation charges for the latest reported financial year'),
					(2, 2, '2120', 'FH-70', 'Enter your organisation''s profit or loss for the latest reported financial year'),
					(2, 2, '2120', 'FH-80', 'Enter your organisation''s total dividends for the latest reported financial year'),
					(2, 2, '2120', 'FH-90', 'Enter your organisation''s total current assets for the latest reported financial year'),
					(2, 2, '2130', 'FH-140', 'Enter your organisation''s total annual turnover for the latest reported financial year'),
					(2, 2, '2130', 'FH-150', 'Enter your organisation''s total depreciation and amortisation charges for the latest reported financial year'),
					(2, 2, '2130', 'FH-160', 'Enter your organisation''s profit or loss for the latest reported financial year'),
					(2, 2, '2130', 'FH-170', 'Enter your organisation''s total dividends for the latest reported financial year'),
					(2, 2, '2130', 'FH-180', 'Enter your organisation''s total current assets for the latest reported financial year'),
					(2, 2, '2130', 'FH-190', 'Enter your organisation''s total current liabilities for the latest reported financial year'),
					(2, 2, '2130', 'FH-200', 'Enter your organisation''s total borrowings for the latest reported financial year'),
					(2, 2, '2130', 'FH-210', 'Enter your organisation''s net assets for the latest reported financial year'),
					(2, 2, '2130', 'FH-220', 'Enter your organisation''s total intangible assets for the latest reported financial year'),
					(2, 2, '2130', 'FH-225', 'Enter your organisation''s average number of Full Time Equivalent (FTE) employees for the last financial year'),
					(2, 2, '2140', 'FH-230', 'Enter your organisation''s total annual turnover for the latest reported financial year'),
					(2, 2, '2140', 'FH-240', 'Enter your organisation''s total depreciation and amortisation charges for the latest reported financial year'),
					(2, 2, '2140', 'FH-250', 'Enter your organisation''s profit or loss for the latest reported financial year'),
					(2, 2, '2140', 'FH-260', 'Enter your organisation''s total dividends for the latest reported financial year'),
					(2, 2, '2140', 'FH-270', 'Enter your organisation''s total current assets for the latest reported financial year'),
					(2, 2, '2140', 'FH-280', 'Enter your organisation''s total current liabilities for the latest reported financial year'),
					(2, 2, '2140', 'FH-290', 'Enter your organisation''s total borrowings for the latest reported financial year'),
					(2, 2, '2140', 'FH-300', 'Enter your organisation''s net assets for the latest reported financial year'),
					(2, 2, '2140', 'FH-310', 'Enter your organisation''s total intangible assets for the latest reported financial year'),
					(2, 2, '2140', 'FH-315', 'Enter your organisation''s average number of Full Time Equivalent (FTE) employees for the last financial year'),
					(2, 2, '2150', 'FH-320', 'Produced full financial statements covering a minimum of 12 months'),
					(2, 2, '2150', 'FHA-320', 'Produced full financial statements covering a minimum of 12 months'),
					(2, 2, '2160', 'FH-330', 'File 1'),
					(2, 2, '2160', 'FH-331', 'File 2'),
					(2, 2, '2160', 'FH-332', 'File 3'),
					(2, 2, '2160', 'FH-333', 'File 4'),
					(2, 2, '2170', 'FH-340', 'Produced financial statements covering any period within the last 12 months'),
					(2, 2, '2190', 'FH-350', 'File 1'),
					(2, 2, '2190', 'FH-351', 'File 2'),
					(2, 2, '2190', 'FH-352', 'File 3'),
					(2, 2, '2190', 'FH-353', 'File 4'),
					(2, 2, '2200', 'FH-360', 'File 1'),
					(2, 2, '2200', 'FH-361', 'File 2'),
					(2, 2, '2200', 'FH-362', 'File 3'),
					(2, 2, '2200', 'FH-363', 'File 4'),
					(2, 2, '2210', 'FH-370', 'Produced full management accounts covering the last 12 months'),
					(2, 2, '2225', 'FH-380', 'File 1'),
					(2, 2, '2225', 'FH-381', 'File 2'),
					(2, 2, '2225', 'FH-382', 'File 3'),
					(2, 2, '2225', 'FH-383', 'File 4'),
					(2, 2, '2240', 'FH-390', 'File 1'),
					(2, 2, '2240', 'FH-391', 'File 2'),
					(2, 2, '2240', 'FH-392', 'File 3'),
					(2, 2, '2240', 'FH-393', 'File 4'),
					(2, 2, '2250', 'FH-400', 'File 1'),
					(2, 2, '2250', 'FH-401', 'File 2'),
					(2, 2, '2250', 'FH-402', 'File 3'),
					(2, 2, '2250', 'FH-403', 'File 4'),
					(2, 2, '2260', 'FH-410', 'Contact name'),
					(2, 2, '2270', 'FH-420', 'Accounting reference date'),
					(2, 2, '2280', 'FH-430', 'Accounting period months covered'),
					(2, 3, '2500', 'FH-500', 'Has consolidated financial statements'),
					(2, 3, '2510', 'FH-510', 'File 1'),
					(2, 3, '2510', 'FH-511', 'File 2'),
					(2, 3, '2510', 'FH-512', 'File 3'),
					(2, 3, '2510', 'FH-513', 'File 4'),
					(2, 3, '2520', 'FH-520', 'Has other active subsidiary companies'),
					(2, 3, '2530', 'FH-530', 'File 1'),
					(2, 3, '2530', 'FH-531', 'File 2'),
					(2, 3, '2530', 'FH-532', 'File 3'),
					(2, 3, '2530', 'FH-533', 'File 4'),
					(2, 3, '2540', 'FH-540', 'File 1'),
					(2, 3, '2540', 'FH-541', 'File 2'),
					(2, 3, '2540', 'FH-542', 'File 3'),
					(2, 3, '2540', 'FH-543', 'File 4'),
					(3, 2, '3100', 'CC-20', 'Has composition with creditors'),
					(3, 2, '3100', 'CC-20-1', 'Give us more information'),
					(3, 2, '3110', 'CC-21', 'Has failed to pay back funds in the last 3 years?'),
					(3, 2, '3100', 'CC-21-1', 'Give us more information'),
					(3, 2, '3120', 'CC-22', 'Has had a contract terminated early by a public body in the last 3 years'),
					(3, 2, '3100', 'CC-22-1', 'Give us more information'),
					(3, 2, '3130', 'CC-23', 'Has withdrawn from a contract with a public body in the last 3 years'),
					(3, 2, '3100', 'CC-23-1', 'Give us more information'),
					(3, 2, '3135', 'CC-235', 'Has been removed from the Register of Training Organisations (RoTO) in the last 3 years'),
					(3, 2, '3100', 'CC-235-1', 'Give us more information'),
					(3, 2, '3140', 'CC-24', 'Has had funding removed from any education bodies in the last 3 years'),
					(3, 2, '3100', 'CC-24-1', 'Give us more information'),
					(3, 2, '3150', 'CC-25', 'Has been removed from any professional or trade registers in the last 3 years'),
					(3, 2, '3100', 'CC-25-1', 'Give us more information'),
					(3, 2, '3160', 'CC-26', 'Has been involuntarily withdrawn from Initial Teacher Training accreditation in the last 3 years'),
					(3, 2, '3100', 'CC-26-1', 'Give us more information'),
					(3, 2, '3170', 'CC-27', 'Has been removed from any charity register'),
					(3, 2, '3100', 'CC-27-1', 'Give us more information'),
					(3, 2, '3180', 'CC-28', 'Has been investigated due to safeguarding issues in the last 3 months'),
					(3, 2, '3100', 'CC-28-1', 'Give us more information'),
					(3, 2, '3190', 'CC-29', 'Currently, or has within the last 5 years been, subject to an investigation by the ESFA or other public body or regulator'),
					(3, 2, '3100', 'CC-29-1', 'Give us more information'),
					(3, 2, '3199', 'CC-30', 'Has been subject to insolvency or winding up proceedings in the last 3 years'),
					(3, 2, '3100', 'CC-30-1', 'Give us more information'),
					(3, 4, '3300', 'CC-40', 'Anyone who''s in control have any unspent criminal convictions'),
					(3, 4, '3100', 'CC-40-1', 'Give us more information'),
					(3, 4, '3301', 'CC-41', 'Have any unspent criminal convictions?'),
					(3, 4, '3100', 'CC-41-1', 'Give us more information'),
					(3, 4, '3310', 'CC-50', 'Has anyone who''s in control failed to pay back funds in the last 3 years'),
					(3, 4, '3100', 'CC-50-1', 'Give us more information'),
					(3, 4, '3311', 'CC-51', 'Have failed to pay back funds in the last 3 years'),
					(3, 4, '3100', 'CC-51-1', 'Give us more information'),
					(3, 4, '3320', 'CC-60', 'Anyone who''s in control of your organisation been investigated for fraud or irregularities in the last 3 years'),
					(3, 4, '3100', 'CC-60-1', 'Give us more information'),
					(3, 4, '3321', 'CC-61', 'Been investigated for fraud or irregularities in the last 3 years'),
					(3, 4, '3100', 'CC-61-1', 'Give us more information'),
					(3, 4, '3330', 'CC-70', 'Anyone who''s in control of your organisation have any ongoing investigations for fraud or irregularities'),
					(3, 4, '3100', 'CC-70-1', 'Give us more information'),
					(3, 4, '3331', 'CC-71', 'Have any ongoing investigations for fraud or irregularities'),
					(3, 4, '3100', 'CC-71-1', 'Give us more information'),
					(3, 4, '3340', 'CC-80', 'Anyone who''s in control of your organisation had a contract terminated by a public body in the last 3 years'),
					(3, 4, '3100', 'CC-80-1', 'Give us more information'),
					(3, 4, '3341', 'CC-81', 'Had a contract terminated by a public body in the last 3 years'),
					(3, 4, '3100', 'CC-81-1', 'Give us more information'),
					(3, 4, '3350', 'CC-90', 'Anyone who''s in control of your organisation withdrawn from a contract with a public body in the last 3 years'),
					(3, 4, '3100', 'CC-90-1', 'Give us more information'),
					(3, 4, '3351', 'CC-91', 'Have withdrawn from a contract with a public body in the last 3 years?'),
					(3, 4, '3100', 'CC-91-1', 'Give us more information'),
					(3, 4, '3360', 'CC-100', 'Anyone who''s in control of your organisation breached tax payments or social security contributions in the last 3 years'),
					(3, 4, '3100', 'CC-100-1', 'Give us more information'),
					(3, 4, '3361', 'CC-101', 'Have breached tax payments or social security contributions in the last 3 years'),
					(3, 4, '3100', 'CC-101-1', 'Give us more information'),
					(3, 4, '3370', 'CC-110', 'Anyone who''s in control of your organisation on the Register of Removed Trustees'),
					(3, 4, '3100', 'CC-110-1', 'Give us more information'),
					(3, 4, '3371', 'CC-111', 'Is on the Register of Removed Trustees?'),
					(3, 4, '3100', 'CC-111-1', 'Give us more information'),
					(3, 4, '3380', 'CC-120', 'Anyone who''s in control of your organisation or any of its partner organisations been made bankrupt in the last 3 years'),
					(3, 4, '3100', 'CC-120-1', 'Give us more information'),
					(3, 4, '3381', 'CC-121', 'Have been made bankrupt in the last 3 years'),
					(3, 4, '3100', 'CC-121-1', 'Give us more information'),
					(3, 4, '3390', 'CC-130', 'Anyone who''s in control of your organisation, or any of its partner organisations, been subject to a prohibition order from the Teaching Regulation Agency on behalf of the Secretary of State for Education'),
					(3, 4, '3100', 'CC-130-1', 'Give us more information'),
					(3, 4, '3391', 'CC-131', 'Have been subject to a prohibition order from the Teaching Regulation Agency on behalf of the Secretary of State for Education'),
					(3, 4, '3100', 'CC-131-1', 'Give us more information'),
					(3, 4, '3395', 'CC-135', 'Anyone who''s in control of your organisation, or any of its partner organisations, been subject to a ban from management or governance of schools'),
					(3, 4, '3100', 'CC-135-1', 'Give us more information'),
					(3, 4, '3396', 'CC-136', 'Have been subject to a ban from  management or governance of schools'),
					(3, 4, '3100', 'CC-136-1', 'Give us more information'),
					(4, 2, '4010', 'PYA-20', 'File'),
					(4, 3, '4020', 'PYA-30', 'File'),
					(4, 4, '4030', 'PYA-40', 'File'),
					(4, 4, '4035', 'PYA-45', 'Full name'),
					(4, 4, '4035', 'PYA-46', 'Email'),
					(4, 4, '4035', 'PYA-47', 'Contact number'),
					(4, 4, '4037', 'PYA-48', 'Includes Prevent Duty Policy'),
					(4, 4, '4038', 'PYA-49', 'File'),
					(4, 5, '4040', 'PYA-50', 'File'),
					(4, 5, '4045', 'PYA-55', 'Full name'),
					(4, 5, '4045', 'PYA-56', 'Email'),
					(4, 5, '4045', 'PYA-57', 'Contact number'),
					(4, 6, '4050', 'PYA-60', 'Will follow its lead provider''s policies and plans'),
					(5, 2, '5100', 'RTE-20', 'Has engaged with employers'),
					(5, 2, '5100', 'RTE-20-1', 'Who have you engaged with?'),
					(5, 2, '5110', 'RTE-21', 'How'),
					(5, 2, '5120', 'RTE-22-1', 'Full name'),
					(5, 2, '5120', 'RTE-22-2', 'Email'),
					(5, 2, '5120', 'RTE-22-3', 'Contact number'),
					(5, 2, '5130', 'RTE-23', 'How'),
					(5, 3, '5200', 'RTE-30', 'File'),
					(5, 3, '5210', 'RTE-31', 'Website link'),
					(5, 4, '5300', 'RTE-40', 'File'),
					(5, 5, '5400', 'RTE-50', 'File'),
					(5, 6, '5500', 'RTE-60', 'Process'),
					(5, 6, '5510', 'RTE-61', 'Process'),
					(5, 7, '5550', 'RTE-65', 'Select an option'),
					(5, 7, '5560', 'RTE-66', 'Select all that apply'),
					(5, 7, '5570', 'RTE-67', 'How'),
					(5, 8, '5600', 'RTE-70', 'Expect to use subcontractors'),
					(5, 8, '5610', 'RTE-71', 'How'),
					(6, 2, '6201', 'PAT-21', 'Select all that apply'),
					(6, 2, '6202', 'PAT-22', 'Select all that apply'),
					(6, 2, '6203', 'PAT-23', 'Select all that apply'),
					(6, 2, '6230', 'PAT-30', 'How'),
					(6, 2, '6250', 'PAT-50', 'Has a transition plan'),
					(6, 2, '6252', 'PAT-52', 'How'),
					(6, 2, '6253', 'PAT-53', 'How'),
					(6, 2, '6254', 'PAT-54', 'Why'),
					(6, 2, '6260', 'PAT-60', 'Has a transition plan'),
					(6, 2, '6262', 'PAT-62', 'How'),
					(6, 2, '6264', 'PAT-64', 'Why'),
					(6, 2, '6270', 'PAT-70', 'How'),
					(6, 2, '6280', 'PAT-80', 'How'),
					(6, 3, '6300', 'PAT-630', 'How'),
					(6, 4, '6400', 'PAT-640', 'How'),
					(6, 4, '6405', 'PAT-6405', 'How'),
					(6, 4, '6410', 'PAT-641', 'How'),
					(6, 4, '6420', 'PAT-642', 'Other ways'),
					(6, 5, '6500', 'PAT-650', 'Forecasted starts'),
					(6, 5, '6510', 'PAT-651', 'When'),
					(6, 5, '6520', 'PAT-652', 'Will recruit new staff'),
					(6, 5, '6530', 'PAT-653', 'Typical ratio'),
					(6, 5, '6540', 'PAT-654', 'How'),
					(6, 6, '6600', 'PAT-660', 'Select all that apply'),
					(6, 6, '6610', 'PAT-661', 'How'),
					(6, 7, '6700', 'PAT-670', 'Building and Street'),
					(6, 7, '6700', 'PAT-671', 'Town or City'),
					(6, 7, '6700', 'PAT-672', 'County'),
					(6, 7, '6700', 'PAT-673', 'Postcode'),
					(7, 2, '7100', 'DAT-10-1', 'Full name'),
					(7, 2, '7100', 'DAT-10-2', 'Email'),
					(7, 2, '7100', 'DAT-10-3', 'Contact number'),
					(7, 2, '7100', 'DAT-10-4', 'Is this person part of any other organisations?'),
					(7, 3, '7200', 'DAT-720', 'Management hierarchy'),
					(7, 4, '7300', 'DAT-40', 'File'),
					(7, 4, '7305', 'DAT-7305', 'How'),
					(7, 4, '7310', 'DAT-41-1', 'Full name'),
					(7, 4, '7310', 'DAT-41-2', 'Email'),
					(7, 4, '7310', 'DAT-41-3', 'Contact number'),
					(7, 4, '7320', 'DAT-42', 'How'),
					(7, 5, '7500', 'DAT-750', 'Has team responsible'),
					(7, 5, '7510', 'DAT-751', 'Has someone responsible'),
					(7, 5, '7520', 'DAT-752', 'Has someone responsible'),
					(7, 5, '7530', 'DAT-753', 'Select an option'),
					(7, 5, '7540', 'DAT-754-1', 'Full name'),
					(7, 5, '7540', 'DAT-754-2', 'How much experience do they have in developing and delivering training?'),
					(7, 5, '7560', 'DAT-756', 'Who has this person worked with to develop and deliver training?'),
					(7, 5, '7570', 'DAT-757', 'How has the team worked with other organisations to develop and deliver training?'),
					(7, 5, '7590', 'DAT-759-1', 'Full name'),
					(7, 5, '7590', 'DAT-759-2', 'Do they have at least 3 months experience in developing and delivering training?'),
					(7, 5, '7591', 'DAT-7591', 'How'),
					(7, 5, '7592', 'DAT-7592', 'How'),
					(7, 5, '7593', 'DAT-7593', 'How'),
					(7, 5, '7594', 'DAT-7594', 'How'),
					(7, 5, '7595', 'DAT-7595', 'How'),
					(7, 6, '7600', 'DAT-7600', 'Select all that apply'),
					(7, 6, '7610', 'DAT-7610-1', 'First name'),
					(7, 6, '7610', 'DAT-7610-2', 'Last name'),
					(7, 6, '7610', 'DAT-7610-3', 'Job role'),
					(7, 6, '7610', 'DAT-7610-4', 'Time in role (years and months)'),
					(7, 6, '7610', 'DAT-7610-5', 'Is this person part of any other organisations?'),
					(7, 6, '7610', 'DAT-7610-6', 'Enter the names of all these organisations'),
					(7, 6, '7610', 'DAT-7610-7', 'Date of birth'),
					(7, 6, '7610', 'DAT-7610-8', 'Email'),
					(7, 6, '7610', 'DAT-7610-9', 'Contact number'),
					(7, 6, '7610A', 'DAT-7610A-1', 'Number of starts'),
					(7, 6, '7610AA', 'DAT-7610AA-1', 'Standards'),
					(7, 6, '7610B', 'DAT-7610B-1', 'Number of employees'),
					(7, 6, '7611', 'DAT-76111', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7611', 'DAT-76112', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7611', 'DAT-76113', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7611', 'DAT-76114', 'Do they have sector or trade body memberships?'),
					(7, 6, '7612', 'DAT-76121', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7613', 'DAT-76131', 'How have they delivered training to apprentices?'),
					(7, 6, '7613', 'DAT-76132', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7613', 'DAT-76133', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7615', 'DAT-7615-1', 'First name'),
					(7, 6, '7615', 'DAT-7615-2', 'Last name'),
					(7, 6, '7615', 'DAT-7615-3', 'Job role'),
					(7, 6, '7615', 'DAT-7615-4', 'Time in role (years and months)'),
					(7, 6, '7615', 'DAT-7615-5', 'Is this person part of any other organisations?'),
					(7, 6, '7615', 'DAT-7615-6', 'Enter the names of all these organisations'),
					(7, 6, '7615', 'DAT-7615-7', 'Date of birth'),
					(7, 6, '7615', 'DAT-7615-8', 'Email'),
					(7, 6, '7615', 'DAT-7615-9', 'Contact number'),
					(7, 6, '7615A', 'DAT-7615A-1', 'Number of starts'),
					(7, 6, '7615AA', 'DAT-7615AA-1', 'Standards'),
					(7, 6, '7615B', 'DAT-7615B-1', 'Number of employees'),
					(7, 6, '7616', 'DAT-76161', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7616', 'DAT-76162', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7616', 'DAT-76163', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7616', 'DAT-76164', 'Do they have sector or trade body memberships?'),
					(7, 6, '7617', 'DAT-76171', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7618', 'DAT-76181', 'How have they delivered training to apprentices?'),
					(7, 6, '7618', 'DAT-76182', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7618', 'DAT-76183', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7620', 'DAT-7620-1', 'First name'),
					(7, 6, '7620', 'DAT-7620-2', 'Last name'),
					(7, 6, '7620', 'DAT-7620-3', 'Job role'),
					(7, 6, '7620', 'DAT-7620-4', 'Time in role (years and months)'),
					(7, 6, '7620', 'DAT-7620-5', 'Is this person part of any other organisations?'),
					(7, 6, '7620', 'DAT-7620-6', 'Enter the names of all these organisations'),
					(7, 6, '7620', 'DAT-7620-7', 'Date of birth'),
					(7, 6, '7620', 'DAT-7620-8', 'Email'),
					(7, 6, '7620', 'DAT-7620-9', 'Contact number'),
					(7, 6, '7620A', 'DAT-7620A-1', 'Number of starts'),
					(7, 6, '7620AA', 'DAT-7620AA-1', 'Standards'),
					(7, 6, '7620B', 'DAT-7620B-1', 'Number of employees'),
					(7, 6, '7621', 'DAT-76211', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7621', 'DAT-76212', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7621', 'DAT-76213', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7621', 'DAT-76214', 'Do they have sector or trade body memberships?'),
					(7, 6, '7622', 'DAT-76221', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7623', 'DAT-76231', 'How have they delivered training to apprentices?'),
					(7, 6, '7623', 'DAT-76232', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7623', 'DAT-76233', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7625', 'DAT-7625-1', 'First name'),
					(7, 6, '7625', 'DAT-7625-2', 'Last name'),
					(7, 6, '7625', 'DAT-7625-3', 'Job role'),
					(7, 6, '7625', 'DAT-7625-4', 'Time in role (years and months)'),
					(7, 6, '7625', 'DAT-7625-5', 'Is this person part of any other organisations?'),
					(7, 6, '7625', 'DAT-7625-6', 'Enter the names of all these organisations'),
					(7, 6, '7625', 'DAT-7625-7', 'Date of birth'),
					(7, 6, '7625', 'DAT-7625-8', 'Email'),
					(7, 6, '7625', 'DAT-7625-9', 'Contact number'),
					(7, 6, '7625A', 'DAT-7625A-1', 'Number of starts'),
					(7, 6, '7625AA', 'DAT-7625AA-1', 'Standards'),
					(7, 6, '7625B', 'DAT-7625B-1', 'Number of employees'),
					(7, 6, '7626', 'DAT-76261', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7626', 'DAT-76262', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7626', 'DAT-76263', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7626', 'DAT-76264', 'Do they have sector or trade body memberships?'),
					(7, 6, '7627', 'DAT-76271', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7628', 'DAT-76281', 'How have they delivered training to apprentices?'),
					(7, 6, '7628', 'DAT-76282', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7628', 'DAT-76283', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7630', 'DAT-7630-1', 'First name'),
					(7, 6, '7630', 'DAT-7630-2', 'Last name'),
					(7, 6, '7630', 'DAT-7630-3', 'Job role'),
					(7, 6, '7630', 'DAT-7630-4', 'Time in role (years and months)'),
					(7, 6, '7630', 'DAT-7630-5', 'Is this person part of any other organisations?'),
					(7, 6, '7630', 'DAT-7630-6', 'Enter the names of all these organisations'),
					(7, 6, '7630', 'DAT-7630-7', 'Date of birth'),
					(7, 6, '7630', 'DAT-7630-8', 'Email'),
					(7, 6, '7630', 'DAT-7630-9', 'Contact number'),
					(7, 6, '7630A', 'DAT-7630A-1', 'Number of starts'),
					(7, 6, '7630AA', 'DAT-7630AA-1', 'Standards'),
					(7, 6, '7630B', 'DAT-7630B-1', 'Number of employees'),
					(7, 6, '7631', 'DAT-76311', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7631', 'DAT-76312', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7631', 'DAT-76313', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7631', 'DAT-76314', 'Do they have sector or trade body memberships?'),
					(7, 6, '7632', 'DAT-76321', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7633', 'DAT-76331', 'How have they delivered training to apprentices?'),
					(7, 6, '7633', 'DAT-76332', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7633', 'DAT-76333', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7635', 'DAT-7635-1', 'First name'),
					(7, 6, '7635', 'DAT-7635-2', 'Last name'),
					(7, 6, '7635', 'DAT-7635-3', 'Job role'),
					(7, 6, '7635', 'DAT-7635-4', 'Time in role (years and months)'),
					(7, 6, '7635', 'DAT-7635-5', 'Is this person part of any other organisations?'),
					(7, 6, '7635', 'DAT-7635-6', 'Enter the names of all these organisations'),
					(7, 6, '7635', 'DAT-7635-7', 'Date of birth'),
					(7, 6, '7635', 'DAT-7635-8', 'Email'),
					(7, 6, '7635', 'DAT-7635-9', 'Contact number'),
					(7, 6, '7635A', 'DAT-7635A-1', 'Number of starts'),
					(7, 6, '7635AA', 'DAT-7635AA-1', 'Standards'),
					(7, 6, '7635B', 'DAT-7635B-1', 'Number of employees'),
					(7, 6, '7636', 'DAT-76361', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7636', 'DAT-76362', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7636', 'DAT-76363', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7636', 'DAT-76364', 'Do they have sector or trade body memberships?'),
					(7, 6, '7637', 'DAT-76371', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7638', 'DAT-76381', 'How have they delivered training to apprentices?'),
					(7, 6, '7638', 'DAT-76382', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7638', 'DAT-76383', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7640', 'DAT-7640-1', 'First name'),
					(7, 6, '7640', 'DAT-7640-2', 'Last name'),
					(7, 6, '7640', 'DAT-7640-3', 'Job role'),
					(7, 6, '7640', 'DAT-7640-4', 'Time in role (years and months)'),
					(7, 6, '7640', 'DAT-7640-5', 'Is this person part of any other organisations?'),
					(7, 6, '7640', 'DAT-7640-6', 'Enter the names of all these organisations'),
					(7, 6, '7640', 'DAT-7640-7', 'Date of birth'),
					(7, 6, '7640', 'DAT-7640-8', 'Email'),
					(7, 6, '7640', 'DAT-7640-9', 'Contact number'),
					(7, 6, '7640A', 'DAT-7640A-1', 'Number of starts'),
					(7, 6, '7640AA', 'DAT-7640AA-1', 'Standards'),
					(7, 6, '7640B', 'DAT-7640B-1', 'Number of employees'),
					(7, 6, '7641', 'DAT-76411', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7641', 'DAT-76412', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7641', 'DAT-76413', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7641', 'DAT-76414', 'Do they have sector or trade body memberships?'),
					(7, 6, '7642', 'DAT-76421', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7643', 'DAT-76431', 'How have they delivered training to apprentices?'),
					(7, 6, '7643', 'DAT-76432', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7643', 'DAT-76433', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7645', 'DAT-7645-1', 'First name'),
					(7, 6, '7645', 'DAT-7645-2', 'Last name'),
					(7, 6, '7645', 'DAT-7645-3', 'Job role'),
					(7, 6, '7645', 'DAT-7645-4', 'Time in role (years and months)'),
					(7, 6, '7645', 'DAT-7645-5', 'Is this person part of any other organisations?'),
					(7, 6, '7645', 'DAT-7645-6', 'Enter the names of all these organisations'),
					(7, 6, '7645', 'DAT-7645-7', 'Date of birth'),
					(7, 6, '7645', 'DAT-7645-8', 'Email'),
					(7, 6, '7645', 'DAT-7645-9', 'Contact number'),
					(7, 6, '7645A', 'DAT-7645A-1', 'Number of starts'),
					(7, 6, '7645AA', 'DAT-7645AA-1', 'Standards'),
					(7, 6, '7645B', 'DAT-7645B-1', 'Number of employees'),
					(7, 6, '7646', 'DAT-76461', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7646', 'DAT-76462', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7646', 'DAT-76463', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7646', 'DAT-76464', 'Do they have sector or trade body memberships?'),
					(7, 6, '7647', 'DAT-76471', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7648', 'DAT-76481', 'How have they delivered training to apprentices?'),
					(7, 6, '7648', 'DAT-76482', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7648', 'DAT-76483', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7650', 'DAT-7650-1', 'First name'),
					(7, 6, '7650', 'DAT-7650-2', 'Last name'),
					(7, 6, '7650', 'DAT-7650-3', 'Job role'),
					(7, 6, '7650', 'DAT-7650-4', 'Time in role (years and months)'),
					(7, 6, '7650', 'DAT-7650-5', 'Is this person part of any other organisations?'),
					(7, 6, '7650', 'DAT-7650-6', 'Enter the names of all these organisations'),
					(7, 6, '7650', 'DAT-7650-7', 'Date of birth'),
					(7, 6, '7650', 'DAT-7650-8', 'Email'),
					(7, 6, '7650', 'DAT-7650-9', 'Contact number'),
					(7, 6, '7650A', 'DAT-7650A-1', 'Number of starts'),
					(7, 6, '7650AA', 'DAT-7650AA-1', 'Standards'),
					(7, 6, '7650B', 'DAT-7650B-1', 'Number of employees'),
					(7, 6, '7651', 'DAT-76511', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7651', 'DAT-76512', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7651', 'DAT-76513', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7651', 'DAT-76514', 'Do they have sector or trade body memberships?'),
					(7, 6, '7652', 'DAT-76521', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7653', 'DAT-76531', 'How have they delivered training to apprentices?'),
					(7, 6, '7653', 'DAT-76532', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7653', 'DAT-76533', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7655', 'DAT-7655-1', 'First name'),
					(7, 6, '7655', 'DAT-7655-2', 'Last name'),
					(7, 6, '7655', 'DAT-7655-3', 'Job role'),
					(7, 6, '7655', 'DAT-7655-4', 'Time in role (years and months)'),
					(7, 6, '7655', 'DAT-7655-5', 'Is this person part of any other organisations?'),
					(7, 6, '7655', 'DAT-7655-6', 'Enter the names of all these organisations'),
					(7, 6, '7655', 'DAT-7655-7', 'Date of birth'),
					(7, 6, '7655', 'DAT-7655-8', 'Email'),
					(7, 6, '7655', 'DAT-7655-9', 'Contact number'),
					(7, 6, '7655A', 'DAT-7655A-1', 'Number of starts'),
					(7, 6, '7655AA', 'DAT-7655AA-1', 'Standards'),
					(7, 6, '7655B', 'DAT-7655B-1', 'Number of employees'),
					(7, 6, '7656', 'DAT-76561', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7656', 'DAT-76562', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7656', 'DAT-76563', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7656', 'DAT-76564', 'Do they have sector or trade body memberships?'),
					(7, 6, '7657', 'DAT-76571', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7658', 'DAT-76581', 'How have they delivered training to apprentices?'),
					(7, 6, '7658', 'DAT-76582', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7658', 'DAT-76583', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7660', 'DAT-7660-1', 'First name'),
					(7, 6, '7660', 'DAT-7660-2', 'Last name'),
					(7, 6, '7660', 'DAT-7660-3', 'Job role'),
					(7, 6, '7660', 'DAT-7660-4', 'Time in role (years and months)'),
					(7, 6, '7660', 'DAT-7660-5', 'Is this person part of any other organisations?'),
					(7, 6, '7660', 'DAT-7660-6', 'Enter the names of all these organisations'),
					(7, 6, '7660', 'DAT-7660-7', 'Date of birth'),
					(7, 6, '7660', 'DAT-7660-8', 'Email'),
					(7, 6, '7660', 'DAT-7660-9', 'Contact number'),
					(7, 6, '7660A', 'DAT-7660A-1', 'Number of starts'),
					(7, 6, '7660AA', 'DAT-7660AA-1', 'Standards'),
					(7, 6, '7660B', 'DAT-7660B-1', 'Number of employees'),
					(7, 6, '7661', 'DAT-76611', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7661', 'DAT-76612', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7661', 'DAT-76613', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7661', 'DAT-76614', 'Do they have sector or trade body memberships?'),
					(7, 6, '7662', 'DAT-76621', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7663', 'DAT-76631', 'How have they delivered training to apprentices?'),
					(7, 6, '7663', 'DAT-76632', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7663', 'DAT-76633', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7665', 'DAT-7665-1', 'First name'),
					(7, 6, '7665', 'DAT-7665-2', 'Last name'),
					(7, 6, '7665', 'DAT-7665-3', 'Job role'),
					(7, 6, '7665', 'DAT-7665-4', 'Time in role (years and months)'),
					(7, 6, '7665', 'DAT-7665-5', 'Is this person part of any other organisations?'),
					(7, 6, '7665', 'DAT-7665-6', 'Enter the names of all these organisations'),
					(7, 6, '7665', 'DAT-7665-7', 'Date of birth'),
					(7, 6, '7665', 'DAT-7665-8', 'Email'),
					(7, 6, '7665', 'DAT-7665-9', 'Contact number'),
					(7, 6, '7665A', 'DAT-7665A-1', 'Number of starts'),
					(7, 6, '7665AA', 'DAT-7665AA-1', 'Standards'),
					(7, 6, '7665B', 'DAT-7665B-1', 'Number of employees'),
					(7, 6, '7666', 'DAT-76661', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7666', 'DAT-76662', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7666', 'DAT-76663', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7666', 'DAT-76664', 'Do they have sector or trade body memberships?'),
					(7, 6, '7667', 'DAT-76671', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7668', 'DAT-76681', 'How have they delivered training to apprentices?'),
					(7, 6, '7668', 'DAT-76682', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7668', 'DAT-76683', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7670', 'DAT-7670-1', 'First name'),
					(7, 6, '7670', 'DAT-7670-2', 'Last name'),
					(7, 6, '7670', 'DAT-7670-3', 'Job role'),
					(7, 6, '7670', 'DAT-7670-4', 'Time in role (years and months)'),
					(7, 6, '7670', 'DAT-7670-5', 'Is this person part of any other organisations?'),
					(7, 6, '7670', 'DAT-7670-6', 'Enter the names of all these organisations'),
					(7, 6, '7670', 'DAT-7670-7', 'Date of birth'),
					(7, 6, '7670', 'DAT-7670-8', 'Email'),
					(7, 6, '7670', 'DAT-7670-9', 'Contact number'),
					(7, 6, '7670A', 'DAT-7670A-1', 'Number of starts'),
					(7, 6, '7670AA', 'DAT-7670AA-1', 'Standards'),
					(7, 6, '7670B', 'DAT-7670B-1', 'Number of employees'),
					(7, 6, '7671', 'DAT-76711', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7671', 'DAT-76712', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7671', 'DAT-76713', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7671', 'DAT-76714', 'Do they have sector or trade body memberships?'),
					(7, 6, '7672', 'DAT-76721', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7673', 'DAT-76731', 'How have they delivered training to apprentices?'),
					(7, 6, '7673', 'DAT-76732', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7673', 'DAT-76733', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7675', 'DAT-7675-1', 'First name'),
					(7, 6, '7675', 'DAT-7675-2', 'Last name'),
					(7, 6, '7675', 'DAT-7675-3', 'Job role'),
					(7, 6, '7675', 'DAT-7675-4', 'Time in role (years and months)'),
					(7, 6, '7675', 'DAT-7675-5', 'Is this person part of any other organisations?'),
					(7, 6, '7675', 'DAT-7675-6', 'Enter the names of all these organisations'),
					(7, 6, '7675', 'DAT-7675-7', 'Date of birth'),
					(7, 6, '7675', 'DAT-7675-8', 'Email'),
					(7, 6, '7675', 'DAT-7675-9', 'Contact number'),
					(7, 6, '7675A', 'DAT-7675A-1', 'Number of starts'),
					(7, 6, '7675AA', 'DAT-7675AA-1', 'Standards'),
					(7, 6, '7675B', 'DAT-7675B-1', 'Number of employees'),
					(7, 6, '7676', 'DAT-76761', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7676', 'DAT-76762', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7676', 'DAT-76763', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7676', 'DAT-76764', 'Do they have sector or trade body memberships?'),
					(7, 6, '7677', 'DAT-76771', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7678', 'DAT-76781', 'How have they delivered training to apprentices?'),
					(7, 6, '7678', 'DAT-76782', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7678', 'DAT-76783', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 6, '7680', 'DAT-7680-1', 'First name'),
					(7, 6, '7680', 'DAT-7680-2', 'Last name'),
					(7, 6, '7680', 'DAT-7680-3', 'Job role'),
					(7, 6, '7680', 'DAT-7680-4', 'Time in role (years and months)'),
					(7, 6, '7680', 'DAT-7680-5', 'Is this person part of any other organisations?'),
					(7, 6, '7680', 'DAT-7680-6', 'Enter the names of all these organisations'),
					(7, 6, '7680', 'DAT-7680-7', 'Date of birth'),
					(7, 6, '7680', 'DAT-7680-8', 'Email'),
					(7, 6, '7680', 'DAT-7680-9', 'Contact number'),
					(7, 6, '7680A', 'DAT-7680A-1', 'Number of starts'),
					(7, 6, '7680AA', 'DAT-7680AA-1', 'Standards'),
					(7, 6, '7680B', 'DAT-7680B-1', 'Number of employees'),
					(7, 6, '7681', 'DAT-76811', 'What''s their experience of delivering training in this sector?'),
					(7, 6, '7681', 'DAT-76812', 'Do they have any qualifications relating to this sector?'),
					(7, 6, '7681', 'DAT-76813', 'Are they approved by awarding bodies to deliver training?'),
					(7, 6, '7681', 'DAT-76814', 'Do they have sector or trade body memberships?'),
					(7, 6, '7682', 'DAT-76821', 'What type of apprenticeship training have they delivered?'),
					(7, 6, '7683', 'DAT-76831', 'How have they delivered training to apprentices?'),
					(7, 6, '7683', 'DAT-76832', 'What''s their experience of delivering training to apprentices?'),
					(7, 6, '7683', 'DAT-76833', 'What''s the typical duration of training they have delivered to apprentices?'),
					(7, 7, '7700', 'DAT-770', 'File'),
					(7, 7, '7710', 'DAT-771', 'Example'),
					(7, 7, '7720', 'DAT-772', 'Example'),
					(8, 2, '8100', 'EAT-20', 'Process'),
					(8, 2, '8110', 'EAT-21', 'How'),
					(8, 3, '8200', 'EAT-30', 'Process includes apprenticeship training?'),
					(8, 3, '8210', 'EAT-40', 'How'),
					(8, 3, '8220', 'EAT-41', 'How'),
					(8, 3, '8230', 'EAT-50', 'How'),
					(8, 4, '8300', 'EAT-60', 'Has systems and processes in place to collect apprenticeship data'),
					(8, 4, '8310', 'EAT-70', 'Has resources to submit Individualised Learner Record (ILR) data'),
					(8, 4, '8320', 'EAT-80', 'Full name'),
					(8, 4, '8320', 'EAT-81', 'Email'),
					(8, 4, '8320', 'EAT-82', 'Contact number'),
					(9, 1, '9000', 'FIN-10', 'Has permission from everyone'),
					(9, 1, '9010', 'FIN-20', 'Has checked details provided from everyone are accurate'),
					(9, 1, '9020', 'FIN-30', 'Has permission to submit this application'),
					(9, 2, '9100', 'FIN-40', 'Has understood organisation must develop and deliver apprenticeship training in line with the Institute for Apprenticeships and Technical Education''s ''quality statement'''),
					(9, 3, '9200', 'FIN-50', 'Has understood organisation will not join the RoATP until it completes all post application tasks');



					DELETE FROM [Mtd].[RP_LookupSectionTitles] 

					/*  Insert into [Mtd].[RP_LookupSectionTitles] */
					INSERT INTO [Mtd].[RP_LookupSectionTitles] 
					([SequenceNumber],[SectionNumber],[Title]) 
					VALUES
						(0, 1, 'Preamble'),
						(1, 1, 'Introduction and what you''ll need'),
						(1, 2, 'Organisation information'),
						(1, 3, 'Confirm who''s in control'),
						(1, 4, 'Describe your organisation'),
						(1, 5, 'Experience and accreditation'),
						(2, 1, 'Introduction and what you''ll need'),
						(2, 2, 'Your organisation''s financial evidence'),
						(2, 3, 'Your UK ultimate parent company''s financial evidence'),
						(3, 1, 'Introduction and what you''ll need'),
						(3, 2, 'Checks on your organisation'),
						(3, 3, 'Introduction and what you''ll need'),
						(3, 4, 'Checks on who''s in control of your organisation'),
						(4, 1, 'Introduction and what you''ll need'),
						(4, 2, 'Continuity plan for apprenticeship training'),
						(4, 3, 'Equality and diversity policy'),
						(4, 4, 'Safeguarding and Prevent duty policy'),
						(4, 5, 'Health and safety policy'),
						(4, 6, 'Acting as a subcontractor'),
						(5, 1, 'Introduction and what you''ll need'),
						(5, 2, 'Engaging with employers'),
						(5, 3, 'Complaints policy'),
						(5, 4, 'Contract for services template'),
						(5, 5, 'Commitment statement template'),
						(5, 6, 'Prior learning of apprentices'),
						(5, 7, 'English and maths assessments'),
						(5, 8, 'Working with subcontractors'),
						(6, 1, 'Introduction and what you''ll need'),
						(6, 2, 'Type of apprenticeship training'),
						(6, 3, 'Training apprentices'),
						(6, 4, 'Supporting apprentices'),
						(6, 5, 'Forecasting starts'),
						(6, 6, 'Off the job training'),
						(6, 7, 'Where will your apprentices be trained'),
						(7, 1, 'Introduction and what you''ll need'),
						(7, 2, 'Overall accountability for apprenticeships'),
						(7, 3, 'Management hierarchy for apprenticeships'),
						(7, 4, 'Quality and high standards in apprenticeship training'),
						(7, 5, 'Developing and delivering training'),
						(7, 6, 'Sectors and employee experience'),
						(7, 7, 'Policy for professional development of employees'),
						(8, 1, 'Introduction and what you''ll need'),
						(8, 2, 'Process for evaluating the quality of training delivered'),
						(8, 3, 'Process of evaluating the quality of apprenticeship training'),
						(8, 4, 'Systems and processes to collect apprenticeship data'),
						(9, 1, 'Application permissions and checks'),
						(9, 2, 'Quality statement'),
						(9, 3, 'Post application tasks'),
						(9, 4, 'Submit application');


						DELETE FROM [Mtd].[RP_LookupSequenceTitles] 
						/* Inserting into [Mtd].[RP_LookupSequenceTitles] */
						INSERT INTO [Mtd].[RP_LookupSequenceTitles] 
						([SequenceNumber],[Title]) 
						VALUES
						(0, 'Preamble'),
						(1, 'Your organisation'),
						(2, 'Financial evidence'),
						(3, 'Criminal and compliance checks'),
						(4, 'Protecting your apprentices'),
						(5, 'Readiness to engage'),
						(6, 'Planning apprenticeship training'),
						(7, 'Delivering apprenticeship training'),
						(8, 'Evaluating apprenticeship training'),
						(9, 'Finish');

COMMIT TRANSACTION
END

/* Update Log Execution Results as Success if the query ran succesfully*/

UPDATE Mgmt.Log_Execution_Results
   SET Execution_Status=1
      ,EndDateTime=getdate()
	  ,FullJobStatus='Pending'
 WHERE LogId=@LogID
   AND RunID=@RunId

 
END TRY

BEGIN CATCH
    IF @@TRANCOUNT>0
	ROLLBACK TRANSACTION

    DECLARE @ErrorId int

  INSERT INTO Mgmt.Log_Error_Details
	  (UserName
	  ,ErrorNumber
	  ,ErrorState
	  ,ErrorSeverity
	  ,ErrorLine
	  ,ErrorProcedure
	  ,ErrorMessage
	  ,ErrorDateTime
	  ,RunId
	  )
  SELECT 
        SUSER_SNAME(),
	    ERROR_NUMBER(),
	    ERROR_STATE(),
	    ERROR_SEVERITY(),
	    ERROR_LINE(),
	    'LoadROATPLookupData',
	    ERROR_MESSAGE(),
	    GETDATE(),
		@RunId as RunId; 

  SELECT @ErrorId=MAX(ErrorId) FROM Mgmt.Log_Error_Details

/* Update Log Execution Results as Fail if there is an Error*/

UPDATE Mgmt.Log_Execution_Results
   SET Execution_Status=0
      ,EndDateTime=getdate()
	  ,ErrorId=@ErrorId
 WHERE LogId=@LogID
   AND RunID=@RunId

  END CATCH

GO
